- type: job
  id: BoSMidKnight
  setPreference: true
  name: job-name-bos-mid-knight
  description: job-description-bos-mid-knight
  playTimeTracker: BoSMidKnight
  startingGear: BoSMidKnight
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  
- type: startingGear
  id: BoSMidKnight
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatBrotherhoodMidwestHelmetVeteran
    outerClothing: N14ClothingOuterMidwestArmorMK2
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidKnight
