- type: job
  id: BoSMidKnight
  setPreference: true
  name: Midwest knight
  description: follow the paladins orders and fight for the brotherhood.
  playTimeTracker: BoSMidKnight
  startingGear: BoSMidKnight
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  
- type: startingGear
  id: BoSMidKnight
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatBrotherhoodMidwestHelmetVeteran
    outerClothing: N14ClothingOuterMidwestArmorMK2
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotag
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidKnight
