- type: job
  id: BoSMidSquire
  setPreference: true
  name: job-name-bos-mid-squire
  description: job-description-bos-mid-squire
  playTimeTracker: BoSMidSquire
  startingGear: BoSMidSquire
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  
- type: startingGear
  id: BoSMidSquire
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatBrotherhoodMidwestHelmet
    outerClothing: N14ClothingOuterMidwestArmor
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidSquire
