- type: job
  id: TownMechanic
  setPreference: true
  name: job-name-townmechanic
  description: job-description-townmechanic
  playTimeTracker: TownMechanic
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 7200 # 2 hours
  startingGear: TownMechanicGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk
  access:
  - TownieMechanic
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

- type: startingGear
  id: TownMechanicGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMechanic
    back: N14ClothingBackpackWastelanderFilled
    shoes: N14ClothingShoesBlack
    id: N14IDPassportTownsfolk
    belt: N14ClothingBeltUtilityFilled
    eyes: N14ClothingEyesGlassesWelding
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: TownMechanic
