- type: job
  id: TownMayor
  setPreference: true
  name: job-name-townmayor
  description: job-description-townmayor
  playTimeTracker: TownMayor
  startingGear: TownMayorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk
  accessGroups:
  - Oasis
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

- type: startingGear
  id: TownMayorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCheckered
    back: N14ClothingBackpackMayorFilled
    shoes: N14ClothingShoesBrown
    id: N14IDBadgeTownMayor
    pocket1: RadioHandheld
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelMayorFilled
  duffelbag: N14ClothingBackpackDuffelMayorFilled

- type: playTimeTracker
  id: TownMayor
