- type: job
  id: PreventorEnforcer
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: preventor enforcer
  description: make sure the vancouver goverment and blue line commercial agreements are accomplished. #need work
  playTimeTracker: PreventorEnforcer
  startingGear: PreventorEnforcerGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: PreventorEnforcerGear
  equipment:
    head: N14ClothingHeadHatVancouver
    back: N14ClothingBackpackMilitaryFilled
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryPreventorFilled
    jumpsuit: N14ClothingUniformJumpsuitVancouver
    shoes: N14ClothingBootsCombat
    gloves: N14ClothingHandsGlovesCombat
    outerClothing: N14ClothingOuterVestLeather
    pocket1: N14WeaponPistol9mm
    pocket2: N14CombatKnife
    suitstorage: N14WeaponRifle556EM2

- type: playTimeTracker
  id: PreventorEnforcer
