- type: job
  id: Survivor
  name: job-name-survivor
  playTimeTracker: Survivor
  startingGear: SurvivorGear
  icon: "Passenger"
  supervisors: job-supervisors-wastelander
  setPreference: false

- type: startingGear
  id: SurvivorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
    pocket1: RadioHandheld
    pocket2: N14KitchenKnife
  innerclothingskirt: N14ClothingUniformJumpskirtMerc
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
