- type: job
  id: BoSMidKnightCommander
  name: job-name-bos-mid-knight-comm
  playTimeTracker: BoSMidKnightCommander
  startingGear: BoSMidKnightCommGear
  icon: "Warden"
  canBeAntag: false
  accessGroups:
  - MidwestBoS
  
- type: startingGear
  id: BoSMidKnightCommGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodHelmetMK2
    jumpsuit: N14ClothingUniformJumpsuitBOSGold
    back: N14ClothingBackpackMilitaryFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterCombatArmorBOSCaptain
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpskirtBOSGold
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
