- type: job
  id: BoSMidScribe
  name: job-name-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  startingGear: BoSMidScribeGear
  departments:
  - Midwest Brotherhood of Steel
  icon: "Scientist"
  supervisors: job-supervisors-bos-mid
  access:
  - MidwestBoSEntrance
  - MidwestBoSCommon
  - MidwestBoSScribe

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
