- type: job
  id: CaravanGuard
  setPreference: true
  name: job-name-caravan-guard
  description: job-description-caravan-guard
  playTimeTracker: CaravanGuard
  startingGear: CaravanGuardGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  alwaysUseSpawner: true
  access:
  - CaravanCompanyGuard
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaravanCompany

- type: startingGear
  id: CaravanGuardGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCaravan
    back: N14ClothingBackpackCaravanFilled
    shoes: N14ClothingBootsLeather
    id: N14IDPassportCaravan
    pocket2: N14WeaponPistol10mm
    outerClothing: N14ClothingOuterLightMetalArmor
    suitstorage: N14WeaponRifle556R91
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled

- type: playTimeTracker
  id: CaravanGuard
