- type: job
  id: Tribal
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-tribal
  description: job-description-tribal
  playTimeTracker: Tribal
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:OverallTimeRequirement
      min: 3600 # 1 hour
  startingGear: TribalGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal
  access:
  - TribeMember
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Tribal
  - !type:AddTraitSpecial
    traits: [ LanguageTribal ]

- type: startingGear
  id: TribalGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    back: N14ClothingBackpackTribalFilled
    pocket1: N14TribalKnife
    id: N14IDTribeBulletsPendant
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalFilled

- type: playTimeTracker
  id: Tribal
