- type: job
  id: TribalElder
  setPreference: true
  name: job-name-tribal-elder
  description: job-description-tribal-elder
  playTimeTracker: TribalElder
  requirements:
    - !type:DepartmentTimeRequirement
      department: Tribe
      min: 7200 # 2 hours
  startingGear: TribalElderGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal-elder
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Tribal

- type: startingGear
  id: TribalElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    suitstorage: N14TribalBigClubDecorated
    outerClothing: N14ClothingOuterTribalCoat
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    back: N14ClothingBackpackTribalFilled
    pocket1: N14TribalKnife
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalFilled

- type: playTimeTracker
  id: TribalElder
