- type: entity
  parent: MobHuman
  id: N14MobHumanTribal
  name: Tribal
  components:
    - type: Icon
      sprite: _Nuclear14/Markers/Jobs/tribal.rsi
      state: tribal
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [TribalGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - Tribal
    - type: LanguageKnowledge
      speaks:
      - English
      - Tribal
      understands:
      - English
      - Tribal

- type: entity
  parent: N14MobHumanTribal
  id: N14MobHumanTribalElder
  name: TribalElder
  components:
    - type: Icon
      state: elder
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [TribalElderGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - Tribal

- type: entity
  parent: N14MobHumanTribal
  id: N14MobHumanTribalFarmer
  name: TribalFarmer
  components:
    - type: Icon
      state: farmer
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [TribalFarmerGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - Tribal

- type: entity
  parent: N14MobHumanTribal
  id: N14MobHumanTribalHealer
  name: TribalHealer
  components:
    - type: Icon
      state: healer
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [TribalHealerGear]
    - type: NpcFactionMember
      factions:
      - Wastelander
      - Tribal

