- type: job
  id: TribalHealer
  setPreference: true
  name: job-name-tribal-healer
  description: job-description-tribal-healer
  playTimeTracker: TribalHealer
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Tribe
      min: 7200 # 2 hours
  startingGear: TribalHealerGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal
  access:
  - TribeMember
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Tribal
      - type: CPRTraining

- type: startingGear
  id: TribalHealerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    back: N14ClothingBackpackTribalHealerFilled
    pocket1: N14TribalKnife
    id: N14IDTribeSawbonePendant
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalHealerFilled

- type: playTimeTracker
  id: TribalHealer
