- type: job
  id: Tribal
  setPreference: true
  name: job-name-tribal
  description: job-description-tribal
  playTimeTracker: Tribal
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:OverallTimeRequirement
      min: 7200 # 2 hours
  startingGear: TribalGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Tribal

- type: startingGear
  id: TribalGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    back: N14ClothingBackpackTribalFilled
    pocket1: N14TribalKnife
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalFilled

- type: playTimeTracker
  id: Tribal
