# Town faction NPCs
- type: startingGear
  id: TownMilitiaNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyBrown
    outerClothing: N14ClothingOuterLightLeatherArmor
    shoes: N14ClothingBootsLeather
    mask: N14ClothingMaskBrownMask

- type: startingGear
  id: TownMilitiaGuardNPC
  equipment:
    jumpsuit: N14ClothingUniformRangerModif
    outerClothing: N14ClothingOuterReinforcedLeatherArmor
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatArmyCap
    gloves: N14ClothingHandsGlovesBrownBiker

# Midwest chapter NPCs
- type: startingGear
  id: MBoSSerfNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSettlerRags
    shoes: N14ClothingShoesTribal
    eyes: ClothingEyesEyepatchColor
    gloves: ClothingHandsGlovesFingerless
    belt: ClothingBeltRope

- type: startingGear
  id: MBoSKnightNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    outerClothing: N14ClothingOuterMBoSKnightArmor
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatArmyCap
    gloves: N14ClothingHandsGlovesBrownBiker

# Washington chapter NPCs
- type: startingGear
  id: WBoSInitiateNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMechanic
    outerClothing: N14ClothingOuterWBoSInitiateArmor
    shoes: N14ClothingBootsBlack
    mask: N14ClothingMaskBrownBalaclava
    belt: ClothingBeltRope

- type: startingGear
  id: WBoSKnightNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    outerClothing: N14ClothingOuterWBoSKnightArmor
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatBrotherhoodBeret
    mask: N14ClothingMaskBlackBalaclava
    gloves: N14ClothingHandsGlovesBlackBiker

# NCR Army NPCs
- type: startingGear
  id: NCRAGuardNPC
  equipment:
    jumpsuit: N14ClothingMPUniformNCRSnow
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesFur
    head: N14ClothingHeadHatNCRHelmetMetalMilitaryPolice
    belt: ClothingBeltRope

- type: startingGear
  id: NCRATrooperNPC
  equipment:
    jumpsuit: N14ClothingUniformNCRSnow
    outerClothing: N14ClothingOuterNCRVestSnow
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatNCRHelmetMetalSnow
    mask: N14ClothingMaskBrownBalaclava
    gloves: N14ClothingHandsGlovesNCR

# Blue Line (Caravan) NPCs
- type: startingGear
  id: CaravanMercNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCaravanOveralls
    outerClothing: N14ClothingOuterPoliceVest
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatArmyBeret

# Tribal faction NPCs
- type: startingGear
  id: TribalSkirmisherNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    shoes: N14ClothingShoesTribal
    head: N14ClothingHeadHatTribalOutcastHood
    gloves: N14ClothingHandsGlovesTribal
    belt: ClothingBeltRope

- type: startingGear
  id: TribalWarriorNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmorHeavy
    shoes: N14ClothingShoesTribal
    head: N14ClothingHeadHatTribalOutcastHood
    neck: N14ClothingNeckCloakYaoguai
  inhand:
  - N14WastelandTribalSpear