- type: startingGear
  id: RaiderPistolGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    shoes: N14ClothingShoesRaider
    mask: N14ClothingMaskBrownMask
    outerClothing: N14ClothingOuterLightMetalArmor
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: RaiderHunterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    shoes: N14ClothingBootsCowboy
    head: N14ClothingHeadHatCowboyBrown
    mask: N14ClothingMaskRedMask
    outerClothing: N14ClothingOuterRaiderBadlands
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: RaiderSkrimisherGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    shoes: N14ClothingBootsLeather
    head: ClothingHeadHelmetBone
    outerClothing: N14ClothingOuterRaiderBlastmaster
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: RaiderBossGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitWastelandDoc
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatBeanie
    mask: N14ClothingMaskBrownMask
    eyes: N14ClothingEyesGlassesWelding
    outerClothing: N14ClothingOuterRaiderCombat1
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: FernMercPrivateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatArmyCap
    mask: N14ClothingMaskBrownMask
    outerClothing: N14ClothingOuterRaiderBadlands
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: FernMercSergeantGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatCombatHelmet
    mask: N14ClothingMaskBrownBalaclava
    eyes: N14ClothingEyesGlassesWelding
    outerClothing: N14ClothingOuterCombatArmor
    belt: ClothingBeltMilitary
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: FernMercLieutenantGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatArmyBeret
    mask: N14ClothingMaskBrownBalaclava
    eyes: N14ClothingEyesSunGlasses
    outerClothing: N14ClothingOuterCombatArmorMK2
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: EnforcerTrooperGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMerc
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatBaseball
    mask: N14ClothingMaskBlueMask
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: EnforcerWardenGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitManagerSuit
    shoes: N14ClothingBootsCombat
    mask: N14ClothingMaskGrill
    outerClothing: N14ClothingOuterPoliceVest
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

- type: startingGear
  id: EnforcerChiefGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitPreWarManager
    shoes: N14ClothingBootsCombatMK2
    head: ClothingHeadHatCowboyBountyHunter
    eyes: N14ClothingEyesSunGlasses
    outerClothing: N14ClothingOuterPoliceChief
    pocket1: N14RaiderStash
  inhand:
  - N14CurrencyCap

#MARK: Melee

- type: startingGear
  id: EnforcerBeatcopGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitManagerSuit
    shoes: N14ClothingBootsFire
    hands: N14ClothingHandsGlovesBlackLeather
    head: N14ClothingHeadHatVaultRiot
    outerClothing: N14ClothingOuterVaultSecVest
    pocket1: N14RaiderStash
  inhand:
  - N14PoliceBaton

- type: startingGear
  id: FernConscriptGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    mask: ClothingMaskBandRed
    eyes: N14ClothingEyesSunGlasses
    shoes: N14ClothingBootsLeather
    hands: N14ClothingHandsGlovesBlackBiker
    head: N14ClothingHeadHatArmyCap
    pocket1: N14RaiderStash
  inhand:
  - N14TrenchClub

- type: startingGear
  id: PsychoRaiderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    eyes: N14ClothingEyesGlassesWelding
    shoes: N14ClothingShoesRaider
    hands: N14ClothingHandsGlovesCloth
    mask: N14ClothingMaskBrownBalaclava
    outerClothing: N14ClothingOuterRaiderBadlands
    pocket1: N14RaiderStash
  inhand:
  - N14KitchenKnife