- type: job
  id: BoSWashingtonKnight
  setPreference: true
  name: job-name-bos-washington-knight
  description: job-description-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 3600 # 1 hour as BoSWashingtonInitiate
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
  startingGear: BoSWashingtonKnightGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2Filled
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterCombatArmorBOS
    id: N14IDBrotherhoodWashingtonHolotagKnight
    belt: ClothingBeltBoSWebbing
    pocket1: NCRBoSWashingtonkits

- type: playTimeTracker
  id: BoSWashingtonKnight
