- type: job
  id: BoSWashingtonKnight
  setPreference: true
  name: job-name-bos-washington-knight
  description: job-description-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 3600 # 1 hour as BoSWashingtonInitiate
  startingGear: BoSWashingtonKnightGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-wash-knight
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterWBoSKnightArmor
    id: N14IDBrotherhoodWashingtonHolotagKnight
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonKnightSet

- type: playTimeTracker
  id: BoSWashingtonKnight
