- type: job
  id: BoSWashingtonPaladin
  setPreference: true
  name: job-name-bos-washington-paladin
  description: job-description-bos-washington-paladin
  playTimeTracker: BoSWashingtonPaladin
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 54000 # 15 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
  startingGear: BoSWashingtonPaladinGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-name-bos-wash
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  - WashingtonScribe
  - WashingtonPaladin
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonPaladinGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsCombatFilled
    outerClothing: N14ClothingOuterWBoSPaladinArmor
    id: N14IDBrotherhoodWashingtonHolotagPaladin
    ears: N14ClothingHeadsetBOSWashington
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonPaladinKits

- type: playTimeTracker
  id: BoSWashingtonPaladin
