- type: job
  id: BoSWashingtonResearcher
  setPreference: true
  name: job-name-bos-washington-researcher
  description: job-description-bos-washington-researcher
  playTimeTracker: BoSWashingtonResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodWashington
      time: 3600 # 1 hour as BosWashingtonRecruit
  startingGear: BoSWashingtonResearcherGear
  alwaysUseSpawner: true
  icon: "JobIconScientist"
  supervisors: job-name-bos-washington
  access:
  - WashingtonInitiate
  - WashingtonScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSWashingtonResearcherGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodBeret
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    satchel: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsCombatFilled
    outerClothing: N14ClothingOuterBosScribe
    id: N14IDBrotherhoodWashingtonHolotagResearcher
    ears: N14ClothingHeadsetBOSWashington
    belt: N14ClothingBeltUtilityFilled

- type: playTimeTracker
  id: BoSWashingtonResearcher
