- type: job
  id: BoSWashingtonScribe # Renamed to Cleric, do not mess with the ID!
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-wash-scribe
  description: job-description-bos-wash-scribe
  playTimeTracker: BoSWashingtonScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 18000 # 5 hours
  startingGear: BoSWashingtonScribeGear
  alwaysUseSpawner: true
  icon: "JobIconScientist"
  supervisors: job-supervisors-bos-wash
  access:
  - WashingtonInitiate
  - WashingtonScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodWashington
      - type: CPRTraining

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackSatchelMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBrotherhoodWashingtonHolotagScribe
    ears: N14ClothingHeadsetBOSWashingtonLightScribe
    pocket1: BoSWashingtonScribeKits

- type: playTimeTracker
  id: BoSWashingtonScribe
