- type: job
  id: BoSWashingtonScribe
  setPreference: true
  name: job-name-bos-washington-scribe
  description: job-description-bos-washington-scribe
  playTimeTracker: BoSWashingtonScribe
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 18000 # 5 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
  startingGear: BoSWashingtonScribeGear
  alwaysUseSpawner: true
  icon: "JobIconScientist"
  supervisors: job-name-bos-washington
  access:
  - WashingtonInitiate
  - WashingtonScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington
      - type: CPRTraining

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodBeret
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsCombatFilled
    outerClothing: N14ClothingOuterBosScribe
    id: N14IDBrotherhoodWashingtonHolotagScribe
    ears: N14ClothingHeadsetBOSWashington
    belt: N14ClothingBeltUtilityFilled
    pocket1: NCRBoSWashingtonScribekits

- type: playTimeTracker
  id: BoSWashingtonScribe
