- type: job
  id: BoSWashingtonSoldier
  setPreference: true
  name: job-name-bos-washington-soldier
  description: job-description-bos-washington-soldier
  playTimeTracker: BoSWashingtonSoldier
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodWashington
      time: 3600 # 1 hour as BosWashingtonRecruit
  startingGear: BoSWashingtonSoldierGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSWashingtonSoldierGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2Filled
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterCombatArmorBOSMK2
    id: N14IDBrotherhoodWashingtonHolotagSoldier
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonSoldier
