- type: job
  id: BoSWashingtonSoldier
  setPreference: true
  name: Washington soldier
  description: Follow your captain orders, no matter how much death they will cause, you follow orders.
  playTimeTracker: BoSWashingtonSoldier
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodWashington
      time: 3600 # 1 hour as BosWashingtonRecruit
  startingGear: BoSWashingtonSoldierGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight

- type: startingGear
  id: BoSWashingtonSoldierGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterCombatArmorBOSMK2
    id: N14IDBrotherhoodHolotag
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonSoldier
