- type: job
  id: BoSMidKnight
  setPreference: true
  name: Midwest knight
  description: follow the paladins orders and fight for the brotherhood.
  playTimeTracker: BoSMidKnight
  requirements:
    - !type:DepartmentTimeRequirement
      department: BoSMidSquire
      time: 3600 # 1 hour
  startingGear: BoSMidKnightGear
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest

- type: startingGear
  id: BoSMidKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatBrotherhoodMidwestHelmetVeteran
    outerClothing: N14ClothingOuterMidwestArmorMK2
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotag
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidKnight
