- type: job
  id: BoSMidKnight
  setPreference: true
  name: job-name-bos-mid-knight
  description: job-description-bos-mid-knight
  playTimeTracker: BoSMidKnight
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodMidwest
      time: 3600 # 1 hour
  startingGear: BoSMidKnightGear
  icon: "JobIconPassenger"
  canBeAntag: false
  access:
  - BoSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSMidKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head: N14ClothingHeadHatBrotherhoodMidwestHelmet
    outerClothing: N14ClothingOuterMidwestArmor
    pocket1: NCRBoSMidwestkits
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotagKnight
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidKnight
