- type: job
  id: BoSMidKnight
  setPreference: true
  name: job-name-bos-mid-knight
  description: job-description-bos-mid-knight
  playTimeTracker: BoSMidKnight
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 18000 # 5 hours
  startingGear: BoSMidKnightGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid-knight
  canBeAntag: false
  access:
  - BoSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest

- type: startingGear
  id: BoSMidKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsCombatFilled
    head: N14ClothingHeadHatBrotherhoodMidwestHelmet
    outerClothing: N14ClothingOuterMidwestArmor
    pocket1: NCRBoSMidwestkits
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotagKnight
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidKnight
