- type: job
  id: BoSMidPaladinCommander
  setPreference: true
  name: job-name-bos-mid-paladin-comm
  description: job-description-bos-mid-paladin-comm
  playTimeTracker: BoSMidPaladinCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodMidwest
      time: 36000 # 10 hours
  startingGear: BoSMidPaladinCommanderGear
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSMidPaladinCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    hands: N14ClothingHandsGlovesCombat
    pocket1: NCRBoSMidwestkits
    id: N14IDBrotherhoodHolotagCommander
    ears: N14ClothingHeadsetBOSMidwest
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidPaladinCommander
