- type: job
  id: BoSMidPaladin
  setPreference: true
  name: job-name-bos-mid-paladin
  description: job-description-bos-mid-paladin
  playTimeTracker: BoSMidPaladin
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodMidwest
      time: 18000 # 5 hours
  startingGear: BoSMidPaladinGear
  icon: "JobIconPassenger"
  canBeAntag: false
  access:
  - BoSMidwest
  - Paladin
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSMidPaladinGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head:  N14ClothingHeadHatBrotherhoodFieldCap
    outerClothing: N14ClothingOuterMidwestArmorMK2
    pocket1: NCRBoSMidwestkits
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotagPaladin
    ears: N14ClothingHeadsetBOSMidwest #placeholder
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSMidPaladin
