- type: job
  id: BoSMidPaladinCommander
  setPreference: true
  name: job-name-bos-mid-paladin-comm
  description: job-description-bos-mid-paladin-comm
  playTimeTracker: BoSMidPaladinCommander
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 72000 # 20 hours
  startingGear: BoSMidPaladinCommanderGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid-commander
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest

- type: startingGear
  id: BoSMidPaladinCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head:  N14ClothingHeadHatBrotherhoodFieldCap
    outerClothing: N14ClothingOuterMidwestArmorMK2
    hands: N14ClothingHandsGlovesCombat
    pocket1: NCRBoSMidwestPaladinkits
    id: N14IDBrotherhoodHolotagCommander
    ears: N14ClothingHeadsetBOSMidwest
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidPaladinCommander
