- type: job
  id: BoSMidScribe
  setPreference: true
  name: Midwest scribe
  description: Maintain equipment and support the knights and paladins in their mission.
  playTimeTracker: BoSMidScribe
  requirements:
    - !type:DepartmentTimeRequirement
      department: BrotherhoodMidwest
      time: 3600 # 1 hour
  startingGear: BoSMidScribeGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid
  access:
  - ScribeMidwest

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    head: ClothingHeadBrotherhoodScribeHeadset
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsCombat
    outerClothing: N14ClothingOuterMidwestBoSCoat
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest
    belt: N14ClothingBeltUtilityFilled

- type: playTimeTracker
  id: BoSMidScribe
