- type: job
  id: BoSMidScribe
  setPreference: true
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 18000 # 5 hours
  startingGear: BoSMidScribeGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid
  access:
  - BoSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest
      - type: CPRTraining
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSScribe
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeather
    pocket1: NCRBoSMidwestScribekits
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest

- type: playTimeTracker
  id: BoSMidScribe
