- type: job
  id: BoSMidSquire # It was renamed to Initiate, but don't change the ID!
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-mid-squire
  description: job-description-bos-mid-squire
  playTimeTracker: BoSMidSquire
  requirements:
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
            - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 3600
  startingGear: BoSMidSquireGear
  alwaysUseSpawner: true
  icon: "JobIconMbosInit"
  supervisors: job-supervisors-bos-mid-initiate
  access:
  - BoSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodMidwest

- type: startingGear
  id: BoSMidSquireGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    head: N14ClothingHeadHatArmyCap
    outerClothing: N14ClothingOuterMBoSInitiateArmor
    pocket1: BoSMidwestInitSet
    id: N14IDBrotherhoodHolotagSquire
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidSquire
