- type: npcFaction
  id: Wastelander
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodMidwest
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodMidwestSecureArea
  hostile:
  - Wastelander
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodWashington
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodWashingtonSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: CaravanCompany
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Feral

- type: npcFaction
  id: CaravanCompanySecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: NCR
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: NCRSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Rangers
  friendly:
  - NCR
  hostile:
  - Zetan
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Feral

- type: npcFaction
  id: Townsfolk
  hostile:
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Tribal
  hostile:
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Vault
  hostile:
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: VaultSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Zetan
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Raider
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  - HostileRobot
  - Feral
  
- type: npcFaction
  id: Feral
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  - HostileRobot
  - Raider

- type: npcFaction
  id: WastelandAnimal
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: WastelandInsect
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: HostileRobot
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - Raider
  - WastelandAnimal
  - Feral