- type: npcFaction
  id: Wastelander

- type: npcFaction
  id: BrotherhoodMidwest
  
- type: npcFaction
  id: BrotherhoodMidwestSecureArea
  hostile:
  - Wastelander
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect

- type: npcFaction
  id: BrotherhoodWashington
  
- type: npcFaction
  id: BrotherhoodWashingtonSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect

- type: npcFaction
  id: CaravanCompany
  
- type: npcFaction
  id: CaravanCompanySecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect

- type: npcFaction
  id: NCR

- type: npcFaction
  id: NCRSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect

- type: npcFaction
  id: Rangers
  friendly:
  - NCR

- type: npcFaction
  id: Townsfolk

- type: npcFaction
  id: Tribal
  
- type: npcFaction
  id: Vault
  
- type: npcFaction
  id: VaultSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  
- type: npcFaction
  id: Zetan
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal
  - WastelandInsect
  
- type: npcFaction
  id: Raider
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  
- type: npcFaction
  id: WastelandAnimal
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  
- type: npcFaction
  id: WastelandInsect
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal