- type: npcFaction
  id: Wastelander
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodMidwest
  friendly:
  - BrotherhoodMidwestSecureArea
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodMidwestSecureArea
  friendly:
  - BrotherhoodMidwest
  hostile:
  - Wastelander
  - BrotherhoodWashington
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodWashington
  friendly:
  - BrotherhoodWashingtonSecureArea
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: BrotherhoodWashingtonSecureArea
  friendly:
  - BrotherhoodWashington
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodMidwestSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: CaravanCompany
  friendly:
  - CaravanCompanySecureArea
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Feral

- type: npcFaction
  id: CaravanCompanySecureArea
  friendly:
  - CaravanCompany
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashington
  - BrotherhoodWashingtonSecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: NCR
  friendly:
  - NCRSecureArea
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: NCRSecureArea
  friendly:
  - NCR
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashington
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Rangers
  friendly:
  - NCR
  hostile:
  - Zetan
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Feral

- type: npcFaction
  id: Townsfolk
  friendly:
  - TownsfolkSecureArea
  hostile:
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: TownsfolkSecureArea
  friendly:
  - Townsfolk
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - Rangers
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Tribal
  friendly:
  - TribalSecureArea
  hostile:
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: TribalSecureArea
  friendly:
  - Tribal
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Vault
  - VaultSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Vault
  friendly:
  - VaultSecureArea
  hostile:
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: VaultSecureArea
  friendly:
  - Vault
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Zetan
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - Vault
  - VaultSecureArea
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: Raider
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  - HostileRobot
  - Feral
  
- type: npcFaction
  id: Feral
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  - HostileRobot
  - Raider

- type: npcFaction
  id: WastelandAnimal
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - WastelandInsect
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: WastelandInsect
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - WastelandAnimal
  - Raider
  - HostileRobot
  - Feral

- type: npcFaction
  id: HostileRobot
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea
  - BrotherhoodWashingtonSecureArea
  - CaravanCompany
  - CaravanCompanySecureArea
  - NCR
  - NCRSecureArea
  - Rangers
  - Townsfolk
  - TownsfolkSecureArea
  - Tribal
  - TribalSecureArea
  - Vault
  - VaultSecureArea
  - WastelandInsect
  - Raider
  - WastelandAnimal
  - Feral