- type: job
  id: BoSWashingtonCaptain
  setPreference: true
  name: job-name-bos-washington-captain
  description: job-description-bos-washington-captain
  playTimeTracker: BoSWashingtonCaptain
  startingGear: BoSWashingtonCaptainGear
  icon: "JobIconPassenger"
  supervisors: job-name-bos-washington
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  - WashingtonScribe
  - WashingtonPaladin

- type: startingGear
  id: BoSWashingtonCaptainGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2
    head: N14ClothingHeadHatBrotherhoodCap
    outerClothing: N14ClothingOuterCombatArmorBOSMK2
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonCaptain
