- type: job
  id: BoSWashingtonKnight
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-knight
  description: job-description-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  startingGear: BoSWashingtonKnightGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonBoSCommon
  - WashingtonBoSEntrance
  - WashingtonBoSKnight
  
- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackMilitaryFilled
    shoes: ClothingShoesBootsJack
    head: N14ClothingHeadHatBrotherhoodHelmetKnight
    outerClothing: N14ClothingOuterCombatArmorBOSKnight
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpskirtBOSBlack
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: BoSWashingtonKnight