- type: job
  id: BoSWashingtonPaladin
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-paladin
  description: job-description-bos-washington-paladin
  playTimeTracker: BoSWashingtonPaladin
  startingGear: BoSWashingtonPaladinGear
  icon: "JobIconPassenger"
  supervisors: job-name-bos-washington
  canBeAntag: false
  access:
  - WashingtonBoSEntrance
  - WashingtonBoSCommon
  - WashingtonBoSPaladin
  - WashingtonBoSKnight

- type: startingGear
  id: BoSWashingtonPaladinGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSSilver
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingShoesBootsJack
    head: N14ClothingHeadHatBrotherhoodHelmetPaladin
    outerClothing: N14ClothingOuterCombatArmorBOSSenior
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSWashington
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpskirtBOSSilver
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: BoSWashingtonPaladin