- type: job
  id: NCRSoldier
  setPreference: true
  name: job-name-ncr-soldier
  description: job-description-ncr-soldier
  playTimeTracker: NCRSoldier
  requirements:
    - !type:DepartmentTimeRequirement
      department: NCR
      time: 3600 # 1 hour
  startingGear: NCRSoldierGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCRCadet
  - NCRSoldier

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetal
    jumpsuit: N14ClothingUniformNCR
    shoes: N14ClothingBootsLeather
    id: N14IDNCRDogtag
  innerClothingSkirt: N14ClothingUniformNCR #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled

- type: playTimeTracker
  id: NCRSoldier
