- type: job
  id: NCRSoldier
  setPreference: true
  name: job-name-ncr-soldier
  description: job-description-ncr-soldier
  playTimeTracker: NCRSoldier
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 3600 # 1 hour
  startingGear: NCRSoldierGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-ncr
  canBeAntag: false
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetalSnow
    back: N14ClothingBackpackNCRFilled
    jumpsuit: N14ClothingUniformNCRSnow
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDNCRDogtag
    pocket1: NCRtrooperloadoutkits
  innerClothingSkirt: N14ClothingUniformNCRSnow #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled

- type: playTimeTracker
  id: NCRSoldier
