- type: job
  id: NCRCadet
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-ncr-cadet
  description: job-description-ncr-cadet
  playTimeTracker: NCRCadet
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 3600
  startingGear: NCRCadetGear
  icon: "JobIconNcrCadet"
  supervisors: job-supervisors-ncr
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRCadetGear
  equipment:
    head: N14ClothingHeadHatNCRSidecap
    back: N14ClothingBackpackNCRFilled
    jumpsuit: N14ClothingUniformNCRSnow
    shoes: N14ClothingBootsLeatherFilled
    pocket1: NCRcadetloadoutkits
    id: N14IDNCRDogtag
  innerClothingSkirt: N14ClothingUniformNCRSnow #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled

- type: playTimeTracker
  id: NCRCadet
