- type: job
  id: NCRSGT
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-sgt
  description: job-description-ncr-sgt
  playTimeTracker: NCRNCO
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 36000 # 10 hours
  startingGear: NCRSGTGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ncr-sgt
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRSGTGear
  equipment:
    back: N14ClothingBackpackRadioNCRFilled
    head: N14ClothingHeadHatNCRHelmetMetalSnow
    gloves: N14ClothingHandsGlovesCombat
    outerClothing: N14ClothingOuterNCRVestSnow
    belt: ClothingBeltNCR
    jumpsuit: N14ClothingUniformNCRSnow
    shoes: N14ClothingBootsCombatFilled
    pocket1: NCRSGTloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagNCO
  innerClothingSkirt: N14ClothingUniformNCRSnow #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled

- type: playTimeTracker
  id: NCRNCO
