- type: job
  id: NCROfficer
  setPreference: true
  name: job-name-ncr-officer
  description: job-description-ncr-officer
  playTimeTracker: NCROfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: NCR
      min: 72000 # 20 hours
  weight: 10
  startingGear: NCROfficerGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR

- type: startingGear
  id: NCROfficerGear
  equipment:
    head: N14ClothingHeadHatNCRBeretOfficer
    back: N14ClothingBackpackNCRFilled
    jumpsuit: N14ClothingOfficerUniformNCRSnow
    shoes: N14ClothingBootsLeather
    belt: ClothingBeltRevolverCaptainfilled
    outerClothing: N14ClothingOuterNCRTrenchCoat
    eyes: ClothingEyesGlassesSunglasses
    pocket1: NCRNCOloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagOfficer
  innerClothingSkirt: N14ClothingOfficerUniformNCRSnow #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled

- type: playTimeTracker
  id: NCROfficer
