- type: job
  id: NCRRangerVeteran
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-ranger-veteran
  description: job-description-ncr-ranger-veteran
  playTimeTracker: NCRRangerVeteran
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRanger
      min: 216000 # 60 hours as NCR
    - !type:CharacterWhitelistRequirement
  startingGear: NCRRangerVeteranGear
  icon: "JobIconNcrVet"
  requireAdminNotify: true
  access:
  - NCR
  - NCRSGT
  - NCRMedic
  - NCRRanger
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRRangerVeteranGear
  equipment:
    jumpsuit: N14ClothingUniformRangerVeteran
    shoes: N14ClothingBootsCombatMK2Filled
    ears: N14ClothingHeadsetNCR
    gloves: N14ClothingHandsGlovesCombat
    belt: ClothingBeltRevolvervetfilled
    mask: ClothingMaskGasRangerOld
    eyes: ClothingEyesGlassesSunglasses
    neck: N14ClothingNeckCloakRanger
    pocket1: MagazineBox45-70
    pocket2: NCRveteranrangerloadoutkits
    outerClothing: N14ClothingOuterRangerCombat
    head: N14ClothingHeadHatRangerHelmetOld
    id: N14IDBadgeNCRRangerElite
    back: N14ClothingBackpackMilitaryFilled
  innerClothingSkirt: N14ClothingUniformRangerModif #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRRangerVeteran
