- type: job
  id: NCRRanger
  setPreference: true
  name: job-name-ncr-ranger
  description: job-description-ncr-ranger
  playTimeTracker: NCRRanger
  requirements:
    - !type:DepartmentTimeRequirement
      department: NCR
      min: 36000 # 10 hours as NCR
    - !type:CharacterWhitelistRequirement
  startingGear: NCRRangerGear
  icon: JobIconSecurityOfficer
  requireAdminNotify: true
  canBeAntag: false
  access:
  - NCR
  - NCRNCO
  - NCRMP
  - NCRRanger
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR

- type: startingGear
  id: NCRRangerGear
  equipment:
    jumpsuit: N14ClothingUniformRangerPatrol
    shoes: N14ClothingBootsCombatFilled
    ears: N14ClothingHeadsetNCR
    belt: ClothingBeltRevolverdesertfilled
    eyes: ClothingEyesGlassesSunglasses
    neck: N14ClothingNeckCloakRangerPoncho
    pocket1: MagazineBox45-70
    pocket2: NCRrangerloadoutkits
    outerClothing: N14ClothingOuterRangerArmor
    head: N14ClothingHeadHatRanger
    id: N14IDBadgeNCRRanger
    back: N14ClothingBackpackMilitaryFilled
  innerClothingSkirt: N14ClothingUniformRangerV3 #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRRanger
