- type: job
  id: NCRRangerVeteran
  setPreference: true
  name: Republic Ranger Veteran
  description: the most experienced and robust soldiers form part of this elite group of the NCR army, lead troops or act by yourself under the orders of the republic.
  playTimeTracker: NCRRangerVeteran
  requirements:
    - !type:DepartmentTimeRequirement
      department: NCR
      time: 72000 # 20 hours as NCR
    - !type:WhitelistRequirement
  weight: 10
  startingGear: NCRRangerVeteranGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR

- type: startingGear
  id: NCRRangerVeteranGear
  equipment:
    jumpsuit: N14ClothingUniformRangerVeteran
    shoes: N14ClothingBootsCombatMK2Filled
    ears: N14ClothingHeadsetNCR
    gloves: N14ClothingHandsGlovesCombat
    belt: ClothingBeltRevolvervetfilled
    mask: ClothingMaskGasRangerOld
    eyes: ClothingEyesGlassesSunglasses
    neck: N14ClothingNeckCloakRanger
    pocket1: MagazineBox45-70
    pocket2: NCRveteranrangerloadoutkits
    outerClothing: N14ClothingOuterRangerCombat
    head: N14ClothingHeadHatRangerHelmetOld
    id: N14IDBadgeNCRRangerElite
    back: N14ClothingBackpackMilitaryFilled
  innerClothingSkirt: N14ClothingUniformRangerModif #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRRangerVeteran
