- type: job
  id: NCRRanger
  setPreference: true
  name: Republic Ranger
  description: the most experienced and robust soldiers form part of this elite group of the NCR army, lead troops or act by yourself under the orders of the republic.
  playTimeTracker: NCRRanger
  requirements:
    - !type:DepartmentTimeRequirement
      department: NCRSoldier
      time: 36000 # 10 hours as NCR Soldier
      department: NCRNCO
      time: 18000 # 5 hours as NCR NCO
      department: NCROfficer
      time: 7200 # 2 hours as NCR Officer
  weight: 5
  startingGear: NCRRangerGear
  icon: JobIconSecurityOfficer
  requireAdminNotify: true
  canBeAntag: false
  access:
  - NCRCadet
  - NCRSoldier
  - NCRNCO
  - NCRRanger

- type: startingGear
  id: NCRRangerGear
  equipment:
    jumpsuit: N14ClothingUniformRangerPatrol
    shoes: N14ClothingBootsCombat
    belt: ClothingBeltRevolverfilled
    eyes: ClothingEyesGlassesSunglasses
    neck: N14ClothingNeckCloakRangerPoncho
    pocket1: MagazineBox44
    pocket2: FlashlightSeclite
    outerClothing: N14ClothingOuterRangerArmor
    head: N14ClothingHeadHatRanger
    id: N14IDBadgeNCRDesertRanger
    back: N14ClothingBackpackMilitaryFilled
  innerClothingSkirt: N14ClothingUniformRangerV3 #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRRanger
