- type: job
  id: TribalElder
  setPreference: false # Delete line for RP
  name: job-name-tribal-elder
  playTimeTracker: TribalElder
  startingGear: TribalElderGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal-elder
  access:
  - Tribal

- type: startingGear
  id: TribalElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmorHeavy
    belt: ClothingBeltPlantFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
