- type: job
  id: Tribal
  setPreference: false # Delete line for RP
  name: job-name-tribal
  description: job-description-tribal
  playTimeTracker: Tribal
  startingGear: TribalGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal

- type: startingGear
  id: TribalGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder

- type: playTimeTracker
  id: Tribal
