- type: job
  id: TribalFarmer
  setPreference: true
  name: job-name-tribal-farmer
  description: job-description-farmer
  playTimeTracker: TribalFarmer
  startingGear: TribalFarmerGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal

- type: startingGear
  id: TribalFarmerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    back: ClothingBackpackHydroponicsFilled #placeholder
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    belt: ClothingBeltPlantFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder

- type: playTimeTracker
  id: TribalFarmer
