- type: job
  id: TribalElder
  setPreference: true
  name: job-name-tribal-elder
  description: job-description-tribal-elder
  playTimeTracker: TribalElder
  startingGear: TribalElderGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal-elder

- type: startingGear
  id: TribalElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmorHeavy
    shoes: N14ClothingShoesTribal
    neck: N14ClothingNeckCloakTribal
    gloves: N14ClothingHandsGlovesTribal
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalFilled

- type: playTimeTracker
  id: TribalElder
