- type: job
  id: TribalElder
  setPreference: false # Delete line for RP
  name: job-name-tribal-elder
  description: job-description-tribal-elder
  playTimeTracker: TribalElder
  startingGear: TribalElderGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal-elder

- type: startingGear
  id: TribalElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmorHeavy
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    belt: ClothingBeltPlantFilled #placeholder
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder

- type: playTimeTracker
  id: TribalElder
