- type: job
  id: TribalHealer
  setPreference: false # Delete line for RP
  name: job-name-tribal-healer
  description: job-description-tribal-healer
  playTimeTracker: TribalHealer
  startingGear: TribalHealerGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal

- type: startingGear
  id: TribalHealerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    back: ClothingBackpackHydroponicsFilled #placeholder
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    belt: ClothingBeltPlantFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder

- type: playTimeTracker
  id: TribalHealer
