- type: job
  id: TribalFarmer
  name: job-name-tribal-farmer
  playTimeTracker: TribalFarmer
  startingGear: TribalFarmerGear
  icon: "Botanist"
  supervisors: job-supervisors-tribal
  access:
  - Tribal

- type: startingGear
  id: TribalFarmerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    back: ClothingBackpackHydroponicsFilled #placeholder
    outerClothing: N14ClothingOuterTribalArmor
    belt: ClothingBeltPlantFilled
  innerclothingskirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
