- type: job
  id: Tribal
  name: job-name-tribal
  playTimeTracker: Tribal
  startingGear: TribalGear
  icon: "Botanist"
  supervisors: job-supervisors-tribal
  access:
  - Tribal

- type: startingGear
  id: TribalGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
  innerclothingskirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
