- type: job
  id: ChineseGunner
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: chinese gunner
  description: follow orders from your superior, fight for the communism with extra fire power. #need work
  playTimeTracker: ChineseGunner
  startingGear: ChineseGunnerGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: ChineseGunnerGear
  equipment:
    head: N14ClothingHeadHatChinese
    back: N14ClothingBackpackMilitaryFilled
    mask: N14ClothingMaskWhiteBalaclava
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryFilled2
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesLeather
    outerClothing: N14ClothingOuterVestChinese
    pocket2: N14CombatKnife
    suitstorage: N14WeaponLMGchinese

- type: playTimeTracker
  id: ChineseGunner
