- type: job
  id: ChineseOfficer
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: chinese officer
  description: lead your troops and fight in the name of communism. #need work
  playTimeTracker: ChineseOfficer
  startingGear: ChineseOfficerGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: ChineseOfficerGear
  equipment:
    head: N14ClothingHeadHatChinese
    back: N14ClothingBackpackMilitaryFilled
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryFilled
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesLeather
    outerClothing: N14ClothingOuterVestChinese
    pocket1: N14WeaponPistol9mmChinese
    pocket2: N14CombatKnife
    suitstorage: N14ChineseSword

- type: playTimeTracker
  id: ChineseOfficer
