- type: job
  id: ChineseRifleman
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: chinese rifleman
  description: follow orders from your superior, fight for the communism. #need work
  playTimeTracker: ChineseRifleman
  startingGear: ChineseRiflemanGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: ChineseRiflemanGear
  equipment:
    head: N14ClothingHeadHatChineseHelmet
    back: N14ClothingBackpackMilitaryFilled
    mask: N14ClothingMaskWhiteBalaclava
    eyes: N14ClothingEyesGlassesGoggles
    belt: ClothingBeltMilitaryFilled3
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesLeather
    outerClothing: N14ClothingOuterVestChinese
    pocket2: N14CombatKnife
    suitstorage: N14WeaponRifle762Chinese

- type: playTimeTracker
  id: ChineseRifleman
