- type: job
  id: ChineseSpecOps
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: chinese spec ops 
  description: follow orders from your superior, fight for the communism. #need work
  playTimeTracker: ChineseSpecOps
  startingGear: ChineseSpecOpsGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: ChineseSpecOpsGear
  equipment:
    head: N14ClothingHeadHatChineseHelmetMk2
    back: N14ClothingBackpackMilitaryFilled
    mask: N14ClothingMaskWhiteBalaclava
    belt: ClothingBeltMilitaryFilled5
    jumpsuit: N14ClothingUniformJumpsuitChinese
    shoes: N14ClothingBootsCombatMK2
    gloves: N14ClothingHandsGlovesCombat
    outerClothing: N14ClothingOuterCombatArmorChinese
    pocket1: N14WeaponPistol9mmChinese
    pocket2: N14CombatKnife
    suitstorage: N14WeaponSMG12mmAdvancedChinese

- type: playTimeTracker
  id: ChineseSpecOps
