- type: job
  id: BoSWashingtonElder
  name: job-name-bos-washington-elder
  weight: 10
  startingGear: BoSWashingtonElderGear
  departments:
  - Washington Brotherhood of Steel
  icon: "HeadOfSecurity"
  supervisors: job-name-bos-washington-elder
  requireAdminNotify: true
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External

- type: startingGear
  id: BoSWashingtonElderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
