- type: job
  id: BoSWashingtonElder
  name: job-name-bos-washington-elder
  playTimeTracker: BoSWashingtonElder
  weight: 10
  startingGear: BoSWashingtonElderGear
  departments:
  - Washington Brotherhood of Steel
  icon: "HeadOfSecurity"
  supervisors: job-supervisors-bos-washington-elder
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - WashingtonBoS

- type: startingGear
  id: BoSWashingtonElderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
