- type: job
  id: BoSWashingtonInitiate
  name: job-name-bos-washington-initiate
  startingGear: BoSWashingtonInitiateGear
  departments:
  - Washington Brotherhood of Steel
  icon: "SecurityCadet"
  supervisors: job-name-bos-washington-initiate
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    id:
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
