- type: job
  id: BoSWashingtonInitiate
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-initiate
  playTimeTracker: BoSWashingtonInitiate
  startingGear: BoSWashingtonInitiateGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-bos-washington-initiate
  canBeAntag: false
  access:
  - WashingtonBoSCommon
  - WashingtonBoSInitiate

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    head: N14ClothingHeadHatBrotherhoodBeret
    back: N14ClothingBackpackMilitaryFilled
    shoes: ClothingShoesBootsJack
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
  innerclothingskirt: ClothingUniformJumpskirtColorRed # TODO: Red jumpskirt for BOS?
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
