- type: job
  id: BoSWashingtonPaladin
  name: job-name-bos-washington-paladin
  playTimeTracker: BoSWashingtonPaladin
  startingGear: BoSWashingtonPaladinGear
  departments:
  - Washington Brotherhood of Steel
  icon: "SecurityOfficer"
  supervisors: job-name-bos-washington
  canBeAntag: false
  access:
  - WashingtonBoSEntrance
  - WashingtonBoSCommon
  - WashingtonBoSPaladin

- type: startingGear
  id: BoSWashingtonPaladinGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetOld
    outerClothing: ClothingOuterVestKevlar
    id:
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
