- type: job
  id: BoSWashingtonScribe
  name: job-name-bos-washington-scribe
  playTimeTracker: BoSWashingtonScribe
  startingGear: BoSWashingtonScribeGear
  departments:
  - Washington Brotherhood of Steel
  icon: "Scientist"
  supervisors: job-name-bos-washington
  access:
  - WashingtonBoSCommon
  - WashingtonBoSScribe

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id:
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
