- type: job
  id: MountieCorporal
  setPreference: true
  name: mountie corporal
  description: follow orders from your sergeant #need work
  playTimeTracker: NCRCadet
  startingGear: MountieCorporalGear
  icon: "JobIconSecurityCadet"

- type: startingGear
  id: MountieCorporalGear
  equipment:
    head: N14ClothingHeadHatMountie
    back: N14ClothingBackpackMilitaryMountieFilled
    belt: ClothingBeltMountieFilled
    jumpsuit: N14ClothingUniformJumpsuitRCMP
    shoes: N14ClothingBootsMountie
    hands: N14ClothingHandsGlovesMountie
    outerclothing: N14ClothingOuterVestRCMP
    pocket1: N14WeaponRevolverWebley
    pocket2: N14CombatKnife
    suitstorage: N14WeaponSniperEnfield
  innerClothingSkirt: N14ClothingUniformJumpsuitRCMP #placeholder
  satchel: N14ClothingBackpackMilitaryMountieFilled

