- type: department
  id: BrotherhoodMidwest
  description: department-BrotherhoodMidwest-description
  color: "#455a64"
  roles:
  - BoSMidPaladinCommander
  - BoSMidSquire
  - BoSMidKnight
  - BoSMidPaladin
  - BoSMidScribe

- type: department
  id: BrotherhoodWashington
  description: department-BrotherhoodWashington-description
  color: "#607d8b"
  roles:
  - BoSWashingtonCommander
  - BoSWashingtonRecruit
  - BoSWashingtonSoldier
  - BoSWashingtonCaptain
  - BoSWashingtonResearcher

- type: department
  id: CaravanCompany
  description: department-CaravanCompany-description
  color: "#a1887f"
  roles:
  - CaravanLeader
  - CaravanTrader

- type: department
  id: NCR
  description: department-NCR-description
  color: "#fbc02d"
  roles:
  - NCRCadet
  - NCRNCO
  - NCRMP
  - NCRQM
  - NCRDoctor
  - NCROfficer
  - NCRSoldier
  - NCRRanger


- type: department
  id: Rangers
  description: department-NCR-description
  color: "#3ab700"
  roles:
  - RangerRecruit
  - Ranger
  - RangerVeteran

- type: department
  id: Tribe
  description: department-Tribe-description
  color: "#5d4037"
  roles:
  - Tribal
  - TribalElder
  - TribalFarmer
  - TribalHealer

- type: department
  id: Vault
  description: department-Vault-description
  color: "#0d47a1"
  roles:
  - Overseer
  - VaultSecurity
  - VaultDoctor
  - VaultDweller
  - VaultEngineer

- type: department
  id: Wastelander
  description: department-Wastelander-description
  color: "#81c784"
  roles:
  - Survivor
  - Wastelander
  - WastelandBartender
  - WastelandChaplain
  - WastelandFarmer
  - WastelandMusician
  - WastelandReporter
  - WastelandScavenger

- type: department
  id: Townsfolk
  description: department-Townsfolk-description
  color: "#5c733a"
  roles:
  - Townsperson
  - TownDoctor
  - TownMechanic
  - TownShopkeeper
  - TownDeputy
  - TownSheriff
  - TownMayor

- type: department
  id: Zetan
  description: department-Zetan-description
  color: "#7ec133"
  roles:
  - Zetan

- type: department
  id: Followers
  description: department-Followers-description
  color: "#33a1c1"
  roles:
  - Followers
