- type: department
  id: BrotherhoodMidwest
  description: department-BrotherhoodMidwest-description
  color: "#455a64"
  roles:
  - BoSMidKnightCommander
  - BoSMidScribe

- type: department
  id: BrotherhoodWashington
  description: department-BrotherhoodWashington-description
  color: "#607d8b"
  roles:
  - BoSWashingtonElder
  - BoSWashingtonInitiate
  - BoSWashingtonKnight
  - BoSWashingtonPaladin
  - BoSWashingtonScribe

- type: department
  id: CaravanCompany
  description: department-CaravanCompany-description
  color: "#a1887f"
  roles:
  - CaravanLeader
  - CaravanTrader

- type: department
  id: NCR
  description: department-NCR-description
  color: "#fbc02d"
  roles:
  - NCRCadet
  - NCRNCO
  - NCROfficer
  - NCRSoldier

- type: department
  id: Tribe
  description: department-Tribe-description
  color: "#5d4037"
  roles:
  - Tribal
  - TribalElder
  - TribalFarmer
  - TribalHealer

- type: department
  id: Vault
  description: department-Vault-description
  color: "#0d47a1"
  roles:
  - Overseer
  - VaultSecurity
  - VaultDoctor
  - VaultDweller
  - VaultEngineer

- type: department
  id: Wastelander
  description: department-Wastelander-description
  color: "#81c784"
  roles:
  - Wastelander
  - WastelandBartender
  - WastelandChaplain
  - WastelandFarmer
  - WastelandMusician
  - WastelandReporter
  - WastelandScavenger