- type: job
  id: Ranger
  setPreference: false
  name: job-name-ranger-ranking
  description: job-description-ranger-ranking
  playTimeTracker: Ranger
  startingGear: RangerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ranger-veteran
  canBeAntag: false
  access:
  - NCR
  - NCRNCO
  - NCRRanger
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Rangers

- type: startingGear
  id: RangerGear
  equipment:
    head: N14ClothingHeadHatRangerHelmetDesert
    back: N14ClothingBackpackMilitaryFilled
    jumpsuit: N14ClothingUniformRangerV2
    ears: N14ClothingHeadsetNCR
    shoes: N14ClothingBootsCombatFilled
    gloves: N14ClothingHandsGlovesBlackLeather
    belt: ClothingBeltRevolverdesertfilled
    mask: ClothingMaskGasRangerDesert
    pocket1: MagazineBox45-70
    pocket2: FlashlightSeclite
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterRangerCombatDesert
    id: N14IDBadgeNCRDesertRanger
  innerClothingSkirt: N14ClothingUniformRangerV1 #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: Ranger
