- type: job
  id: Overseer
  name: job-name-overseer
  playTimeTracker: Overseer
  weight: 20
  startingGear: OverseerGear
  departments:
  - Vault Dwellers
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: job-supervisors-vault-overseer
  accessGroups:
  - VaultOverseer

- type: startingGear
  id: OverseerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
