- type: job
  id: VaultDoctor
  name: job-name-vault-doctor
  playTimeTracker: VaultDoctor
  startingGear: VaultDoctorGear
  departments:
  - Vault Dwellers
  icon: "MedicalDoctor"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller
  - VaultMedical

- type: startingGear
  id: VaultDoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
