- type: job
  id: VaultDweller
  name: job-name-vault-dweller
  playTimeTracker: VaultDweller
  startingGear: VaultDwellerGear
  icon: "Passenger"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller

- type: startingGear
  id: VaultDwellerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultDwellerFilled
    shoes: ClothingShoesColorBlack
    id: N14VaultPDA
    ears: N14ClothingHeadsetVaultDweller
  innerclothingskirt: N14ClothingUniformJumpsuitVault14
