- type: job
  id: VaultDweller
  name: job-name-vault-dweller
  playTimeTracker: VaultDweller
  startingGear: VaultDwellerGear
  icon: "Passenger"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller

- type: startingGear
  id: VaultDwellerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitVault14
    shoes: ClothingShoesColorBlack
    id: PassengerPDA #placeholder
    ears: ClothingHeadsetGrey #placeholder
  innerclothingskirt: ClothingUniformJumpsuitVault14
