- type: job
  id: VaultDoctor
  name: job-name-vault-doctor
  playTimeTracker: VaultDoctor
  startingGear: VaultDoctorGear
  icon: "MedicalDoctor"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller
  - VaultMedical

- type: startingGear
  id: VaultDoctorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultDoctorFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: N14VaultDoctorPDA
    ears: N14ClothingHeadsetVaultMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: N14ClothingUniformJumpsuitVault14
  satchel: N14ClothingBackpackVaultDoctorFilled
  duffelbag: N14ClothingBackpackVaultDoctorFilled
