- type: job
  id: VaultSecurity
  name: job-name-vault-security
  playTimeTracker: VaultSecurity
  startingGear: VaultSecurityGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-overseer
  canBeAntag: false
  access:
  - VaultDweller
  - VaultSecurity

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesSunglasses
    head: ClothingHeadHelmetHelmetOld
    outerClothing: N14ClothingOuterVaultSecVest
    id: N14VaultSecurityPDA
    ears: N14ClothingHeadsetVaultSecurity
    belt: N14ClothingBeltPoliceFilled
  innerclothingskirt: N14ClothingUniformJumpsuitVault14 #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
