- type: job
  id: VaultSecurity
  name: job-name-vault-security
  startingGear: VaultSecurityGear
  departments:
  - Vault Dwellers
  icon: "SecurityOfficer"
  supervisors: job-supervisors-overseer
  canBeAntag: false
  access:
  - Security

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetOld
    outerClothing: ClothingOuterVestKevlar
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
