- type: job
  id: VaultDweller
  name: job-name-vault-dweller
  startingGear: VaultDwellerGear
  departments:
  - Vault Dwellers
  icon: "Passenger"
  supervisors: job-supervisors-overseer
  access:
  - Maintenance

- type: startingGear
  id: VaultDwellerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
