- type: startingGear
  id: TownDeputyGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSheriff
    head: N14ClothingHeadHatDeputy
    eyes: N14ClothingEyesSunGlasses 
    back: N14ClothingBackpackDeputyFilled
    shoes: N14ClothingShoesBlack
    id: N14IDBadgeTownDeputy
    outerClothing: N14ClothingOuterPoliceVest
    belt: ClothingBeltRevolverfilled
    pocket1: RadioHandheld
    pocket2: Handcuffs
  satchel: N14ClothingBackpackSatchelDeputyFilled
  duffelbag: N14ClothingBackpackDuffelDeputyFilled

- type: startingGear
  id: TownSheriffGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSheriff
    back: N14ClothingBackpackSheriffFilled
    shoes: N14ClothingBootsCowboy
    head: N14ClothingHeadHatSheriff
    eyes: N14ClothingEyesSunGlasses 
    id: N14IDBadgeTownSheriff
    outerClothing: N14ClothingOuterSheriffVest
    belt: ClothingBeltRevolverWildWhisper
    neck: N14ClothingNeckMantleSheriff
    mask: N14ClothingMaskSheriff
    pocket1: RadioHandheld
    pocket2: Handcuffs 
  satchel: N14ClothingBackpackSatchelSheriffFilled
  duffelbag: N14ClothingBackpackDuffelSheriffFilled
