- type: job
  id: CaravanLeader
  name: job-name-caravan-leader
  playTimeTracker: CaravanLeader
  weight: 10
  startingGear: CaravanLeaderGear
  icon: "QuarterMaster"
  canBeAntag: false
  supervisors: job-supervisors-caravan-leader
  accessGroups:
  - CaravanCompany

- type: startingGear
  id: CaravanLeaderGear
  equipment:
    head: ClothingHeadHatTrucker
    jumpsuit: N14ClothingUniformJumpsuitMerchant
    back: N14ClothingBackpackCaravanFilled
    shoes: ClothingShoesColorBrown
    id: #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitMerchant #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled
