- type: entity
  parent: MobHuman
  id: N14MobHumanFollowers
  name: Followers
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [FollowersGear]
    - type: NpcFactionMember
      factions:
      - Wastelander

- type: entity
  parent: MobHuman
  id: N14MobHumanSurvivor
  name: Survivor
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [SurvivorGear]
    - type: NpcFactionMember
      factions:
      - Wastelander

- type: entity
  parent: MobHuman
  id: N14MobHumanZetan
  name: Zetan
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [ZetanGear]
    - type: NpcFactionMember
      factions:
      - Zetan

#TODO ROBOT
