- type: job
  id: Survivor
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-survivor
  description: job-description-survivor
  playTimeTracker: Survivor
  startingGear: SurvivorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-wastelander
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: SurvivorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
    pocket1: RadioHandheld
    pocket2: N14KitchenKnife
  innerClothingSkirt: N14ClothingUniformJumpskirtMerc
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: Survivor