- type: job
  id: VaultSecurity
  name: job-name-vault-security
  description: job-description-vault-security
  playTimeTracker: VaultSecurity
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement
    department: Vault
    min: 18000 # 5 hours
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  startingGear: VaultSecurityGear
  alwaysUseSpawner: true
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-vault
  access:
  - VaultDweller
  - VaultSecurity
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Vault

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultSecurityFilled
    shoes: N14ClothingBootsBlack
    eyes: N14ClothingEyesSunGlasses
    head: N14ClothingHeadHatVaultRiot
    outerClothing: N14ClothingOuterVaultSecVest
    id: N14VaultSecurityPDA
    pocket1: N14WeaponPistol10mm
    pocket2: Handcuffs
    ears: N14ClothingHeadsetVaultDweller
    belt: N14PoliceBaton
- type: playTimeTracker
  id: VaultSecurity
