- type: job
  id: VaultSecurity
  setPreference: false # Delete line for RP
  name: job-name-vault-security
  description: job-description-vault-security
  playTimeTracker: VaultSecurity
  requirements:
    - !type:DepartmentTimeRequirement
      department: VaultDweller
      time: 7200 # 2 hours
  startingGear: VaultSecurityGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-overseer
  canBeAntag: false
  access:
  - VaultDweller
  - VaultSecurity

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultSecurityFilled
    shoes: N14ClothingBootsBlack
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHelmetRiot
    outerClothing: N14ClothingOuterVaultSecVest
    id: N14VaultSecurityPDA
    pocket1: N14WeaponPistol10mm
    ears: N14ClothingHeadsetVaultSecurity
    belt: N14ClothingBeltPoliceFilled

- type: playTimeTracker
  id: VaultSecurity
