- type: job
  id: WastelandChaplain
  setPreference: true
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: WastelandChaplain
  startingGear: WastelandChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-wastelander
  access:
  - WastelandChaplain
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: WastelandChaplainGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFollowers
    back: N14ClothingBackpackChaplainFilled
    shoes: N14ClothingBootsBlack
    id: N14IDPassportWasteChaplain
  innerClothingSkirt: N14ClothingUniformJumpsuitFollowers
  satchel: N14ClothingBackpackSatchelChaplainFilled
  duffelbag: N14ClothingBackpackDuffelChaplainFilled

- type: playTimeTracker
  id: WastelandChaplain
