- type: job
  id: WastelandMusician
  setPreference: false # Disabled, use loadouts
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-waste-musician
  description: job-description-waste-musician
  playTimeTracker: WastelandMusician
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 999999
  startingGear: WastelandMusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: WastelandMusicianGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitManagerSuit
    back: N14ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: N14ClothingShoesBrown
  satchel: N14ClothingBackpackSatchelMusicianFilled
  duffelbag: N14ClothingBackpackDuffelMusicianFilled

- type: playTimeTracker
  id: WastelandMusician
