- type: job
  id: Wastelander
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-wastelander
  description: job-description-wastelander
  playTimeTracker: Wastelander
  startingGear: WastelanderGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-wastelander
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: WastelanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: N14ClothingBackpackWastelanderFilled
    shoes: N14ClothingShoesRags
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: Wastelander
