- type: job
  id: CaravanTrader
  setPreference: false # Delete line for RP
  name: job-name-caravan-trader
  description: job-description-caravan-trader
  playTimeTracker: CaravanTrader
  startingGear: CaravanTraderGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: CaravanTraderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTrader
    back: N14ClothingBackpackCaravanFilled
    shoes: N14ClothingShoesRags
    id: N14IDPassportCaravan
  innerclothingskirt: N14ClothingUniformJumpsuitTrader #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled

- type: playTimeTracker
  id: CaravanTrader