- type: job
  id: CaravanLeader
  setPreference: false # Delete line for RP
  name: job-name-caravan-leader
  description: job-description-caravan-leader
  playTimeTracker: CaravanLeader
  weight: 10
  startingGear: CaravanLeaderGear
  icon: "JobIconQuarterMaster"
  canBeAntag: false
  supervisors: job-supervisors-caravan-leader
  accessGroups:
  - CaravanCompany

- type: startingGear
  id: CaravanLeaderGear
  equipment:
#    head: ClothingHeadHatTrucker
    jumpsuit: N14ClothingUniformJumpsuitMerchant
    back: N14ClothingBackpackCaravanFilled
    shoes: N14ClothingShoesBootsCowboyBrown
    id: N14IDPassportCaravan
  innerclothingskirt: N14ClothingUniformJumpsuitMerchant #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled

- type: playTimeTracker
  id: CaravanLeader