- type: job
  id: CaravanGuard
  setPreference: true
  name: job-name-caravan-guard
  description: job-description-caravan-guard
  playTimeTracker: CaravanGuard
  startingGear: CaravanGuardGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  access:
  - CaravanCompanyGuard

- type: startingGear
  id: CaravanGuardGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCaravan
    back: N14ClothingBackpackCaravanFilled
    shoes: N14ClothingBootsCombat
    id: N14IDPassportCaravan
    pocket2: N14WeaponPistol10mm
    outerClothing: N14ClothingOuterLightMetalArmor
    suitstorage: N14WeaponRifleR91

- type: playTimeTracker
  id: CaravanGuard
