- type: job
  id: CaravanGuard
  setPreference: false # Delete line for RP
  name: job-name-caravan-guard
  description: job-description-caravan-guard
  playTimeTracker: CaravanGuard
  startingGear: CaravanGuardGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: CaravanGuardGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCaravan
    back: N14ClothingBackpackCaravanFilled
    shoes: N14ClothingShoesRags
    id: N14IDPassportCaravan
  innerclothingskirt: N14ClothingUniformJumpsuitTrader #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled

- type: playTimeTracker
  id: CaravanGuard
