- type: job
  id: CaravanGuard
  setPreference: true
  name: job-name-caravan-guard
  description: job-description-caravan-guard
  playTimeTracker: CaravanGuard
  startingGear: CaravanGuardGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  access:
  - CaravanCompanyGuard

- type: startingGear
  id: CaravanGuardGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCaravan
    back: N14ClothingBackpackCaravanFilled
    shoes: ClothingShoesColorBlack
    id: N14IDPassportCaravan
  innerClothingSkirt: N14ClothingUniformJumpsuitTrader #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled

- type: playTimeTracker
  id: CaravanGuard
