- type: job
  id: TownMayor
  setPreference: false # Delete line for RP
  name: job-name-townmayor
  description: job-description-townmayor
  playTimeTracker: TownMayor
  startingGear: TownMayorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownMayorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCheckered
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
    id: N14IDBadgeTownMayor
    pocket1: RadioHandheld
  innerclothingskirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: TownMayor