- type: job
  id: TownDeputy
  setPreference: false # Delete line for RP
  name: job-name-towndeputy
  description: job-description-towndeputy
  playTimeTracker: TownDeputy
  startingGear: TownDeputyGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownDeputyGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyBrown
    head: N14ClothingHeadHatDeputy
    back: N14ClothingBackpackDeputyFilled
    shoes: N14ClothingShoesBlack
    id: N14IDBadgeTownDeputy
    outerClothing: N14ClothingOuterLightMetalArmor
    pocket1: RadioHandheld
    pocket2: N14WeaponRevolver10mm
    belt: N14ClothingBeltPoliceFilled
    suitstorage: N14WeaponLeverCarbine

- type: playTimeTracker
  id: TownDeputy
