- type: job
  id: TownDeputy
  setPreference: true
  name: job-name-towndeputy
  description: job-description-towndeputy
  playTimeTracker: TownDeputy
  startingGear: TownDeputyGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownDeputyGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyBrown
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
    id: N14IDBadgeTownDeputy
    outerClothing: N14ClothingOuterLeatherArmor
    pocket1: RadioHandheld
    belt: N14ClothingBeltPoliceFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: TownDeputy