- type: job
  id: TownSheriff
  setPreference: true
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  startingGear: TownSheriffGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownSheriffGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyGrey
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
    id: N14IDBadgeTownSheriff
    outerClothing: N14ClothingOuterCombatArmor
    pocket1: RadioHandheld
    belt: N14ClothingBeltPoliceFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: TownSheriff