#weapons
- type: loadout
  id: N14VaultWeaponPistol9mm
  category: Weapons
  cost: 2
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - VaultSecurity
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutGuns
  items:
    - N14WeaponPistol9mm

- type: loadout
  id: N14VaultWeaponPistol10mmRevolver
  category: Weapons
  cost: 3
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - VaultSecurity
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutGuns
  items:
    - N14WeaponRevolver10mm


# Ammo
- type: loadout
  id: N14VaultSpeedLoader10mm
  category: Weapons
  cost: 1
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - VaultSecurity
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutAmmo
  items:
    - SpeedLoader10

- type: loadout
  id: N14Vault9mmMag
  category: Weapons
  cost: 1
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - VaultSecurity
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutAmmo
  items:
    - N14MagazinePistol9mm