- type: loadout
  id: LoadoutBoSMidwestT45
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
  items:
    - N14ClothingOuterPowerArmorT45

- type: loadout
  id: LoadoutBoSMidwestReconArmor
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: 
      - BoSMidPaladin
      - BoSMidPaladinCommander
      min: 54000 # 15 hours veterancy unlock
  items:
    - N14ClothingOuterMidwestReconArmor

- type: loadout
  id: LoadoutBoSMidwestReconHelmet
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: 
      - BoSMidPaladin
      - BoSMidPaladinCommander
      min: 54000 # 15 hours veterancy unlock
  items:
    - N14ClothingHeadHatBrotherhoodMidwestHelmetRecon

- type: loadout
  id: LoadoutBoSMidwestT60
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterPowerArmorT60

- type: loadout
  id: LoadoutBoSMidwestT51C
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingOuterPowerArmorT51

- type: loadout
  id: LoadoutBoSMidwestT51BC
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladinCommander
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterPowerArmorT51BC
