- type: loadout
  id: LoadoutBoSWashingtonSquire
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonInitiate
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonInitiate
      min: 144000 # 40 hours veterancy unlock
  items:
    - N14ClothingOuterWBoSSquireArmor

- type: loadout
  id: LoadoutBoSWashingtonSeniorKnight
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonKnight
      min: 144000 # 40 hours veterancy unlock
  items:
    - N14ClothingOuterWBoSSeniorKArmor

- type: loadout
  id: LoadoutBoSWashingtonFieldScribe
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonScribe
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonScribe
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingUniformJumpsuitBOSWashingtonFieldScribe

- type: loadout
  id: LoadoutBoSWashingtonPA
  category: Outer
  cost: 9
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
        - BoSWashingtonCommander
  items:
    - N14ClothingOuterPowerArmorWash51

- type: loadout
  id: LoadoutBoSWashingtonPACommander
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonCommander
  items:
    - N14ClothingOuterPowerArmorWash51Elite