# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerVest
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerArmorB
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerArmorB

- type: loadout
  id: LoadoutNCRRangerDuster
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerDuster

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRmaskBroken
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerBroken

- type: loadout
  id: LoadoutNCRmaskCombat
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasCombat

# MARK: Ranger + Vet

- type: loadout
  id: LoadoutNCR308
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox308

- type: loadout
  id: LoadoutNCR20gauge
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MagazineShotgun20
    - N14MagazineShotgun20
    - MagazineBox20gauge

- type: loadout
  id: LoadoutNCR44
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox44
    - MagazineBox44

- type: loadout
  id: LoadoutNCRhatB
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatGrey
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatCowboyGrey

- type: loadout
  id: LoadoutNCRhatGreyBanded
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatCowboyGreyBanded

- type: loadout
  id: LoadoutNCRhatBeret
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRuniformPants
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPants

- type: loadout
  id: LoadoutNCRgloves
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHandsGlovesNCR

# misc
- type: loadout
  id: LoadoutNCRRangerMedkit
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MedkitCombatFilled

- type: loadout
  id: LoadoutNCR556
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - LongMagazine556Rifle
    - LongMagazine556Rifle
    - MagazineBox556

- type: loadout
  id: LoadoutNCR762
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - Magazine762Rifle
    - Magazine762Rifle
    - MagazineBox762

- type: loadout
  id: LoadoutNCR12gauge
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MagazineShotgun12
    - N14MagazineShotgun12
    - MagazineBox12gauge

- type: loadout
  id: LoadoutNCR45-70
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox45-70
    - MagazineBox45-70

# MARK: Ranger Vet

- type: loadout
  id: LoadoutNCR50
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - MagazineBox50
    - MagazineBox50

- type: loadout
  id: LoadoutNCRuniformModif
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerModif

- type: loadout
  id: LoadoutNCRuniformBlue
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerBlue

- type: loadout
  id: LoadoutNCRuniformBlack
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranBlack

- type: loadout
  id: LoadoutNCRuniformRed
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranRed
