#MARK: NCR

- type: loadout
  id: LoadoutNCRKitRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitRifleman

- type: loadout
  id: LoadoutNCRKitMorale
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMorale

- type: loadout
  id: LoadoutNCRKitGunner
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitGunner

- type: loadout
  id: LoadoutNCRKitMarksman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMarksman

- type: loadout
  id: LoadoutNCRKitPointman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitPointman

- type: loadout
  id: LoadoutNCRKitMedic
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMedic

- type: loadout
  id: LoadoutNCRKitSpecialRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialRifleman

- type: loadout
  id: LoadoutNCRKitSpecialAssault
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialAssault

- type: loadout
  id: LoadoutNCRKitSpecialGunner
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialGunner

- type: loadout
  id: LoadoutNCRKitSpecialPointman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialPointman

#MARK: Republic Rangers

- type: loadout
  id: LoadoutRangerKitService
  category: Roles
  cost: 8
  exclusive: true
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - KitServiceRanger

- type: loadout
  id: LoadoutRangerKitRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - KitRiflemanRanger

- type: loadout
  id: LoadoutRangerKitMarksman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - KitMarksmanRanger

- type: loadout
  id: LoadoutRangerKitCQB
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - KitCQBRanger

- type: loadout
  id: LoadoutVeteranRangerKitService
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - KitServiceRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - KitRiflemanRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitHeavySniper
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - KitHeavySniperRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitTrailman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - KitTrailmanRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitAssault
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - KitAssaultRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitMarksman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - KitMarksmanRangerVeteran

