- type: loadout
  id: LoadoutBoSWashingtonT45
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
  items:
    - N14ClothingOuterPowerArmorT45

- type: loadout
  id: LoadoutBoSWashingtonMK3Armor
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
        - BoSWashingtonCommander
    - !type:CharacterPlaytimeRequirement
      tracker: 
      - BoSWashingtonPaladin
      - BoSWashingtonCommander
      min: 54000 # 15 hours veterancy unlock
  items:
    - N14ClothingOuterCombatArmorMK3

- type: loadout
  id: LoadoutBoSWashingtonMK3Helmet
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
        - BoSWashingtonCommander
    - !type:CharacterPlaytimeRequirement
      tracker:
      - BoSWashingtonPaladin
      - BoSWashingtonCommander
      min: 54000 # 15 hours veterancy unlock
  items:
    - N14ClothingHeadHatBrotherhoodHelmetMK3

- type: loadout
  id: LoadoutBoSWashingtonT60
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonPaladin
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterPowerArmorT60

- type: loadout
  id: LoadoutBoSWashingtonT51C
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonCommander
  items:
    - N14ClothingOuterPowerArmorT51

- type: loadout
  id: LoadoutBoSWashingtonT51BC
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonCommander
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterPowerArmorT51BC

- type: loadout
  id: LoadoutBoSWashingtonCoat
  category: Roles
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonCommander
        - BoSWashingtonKnight
        - BoSWashingtonScribe
        - BoSWashingtonPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonKnight
      min: 54000
  items:
    - N14ClothingOuterBrotherhoodWashingtonCoat
