- type: loadout
  id: LoadoutBoSMidwestSquire
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidSquire
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidSquire
      min: 144000 # 40 hours veterancy unlock
  items:
    - N14ClothingOuterMBoSSquireArmor

- type: loadout
  id: LoadoutBoSMidwestSeniorKnight
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidKnight
      min: 144000 # 40 hours veterancy unlock
  items:
    - N14ClothingOuterMBoSSeniorKArmor

- type: loadout
  id: LoadoutBoSMidwestFieldScribe
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidScribe
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingUniformJumpsuitBOSFieldScribe

- type: loadout
  id: LoadoutBoSMidwestPA
  category: Outer
  cost: 9
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
        - BoSMidPaladinCommander
  items:
    - N14ClothingOuterPowerArmorMidwest

- type: loadout
  id: LoadoutBoSMidwestPACommander
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingOuterPowerArmorMidwestCommander
