#mark Tribe 

- type: loadout
  id: N14ClothingHeadHatTribalPowerhelm
  category: Head
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
    - !type:CharacterPlaytimeRequirement
      tracker: TribalElder
      min: 36000 # 10 hours veterancy unlock
  items:
    - N14ClothingHeadHatTribalPowerhelm

- type: loadout
  id: N14TribalSword
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalSword

- type: loadout
  id: N14ClothingOuterElderwintercoat
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingOuterElderwintercoat

- type: loadout
  id: N14ClothingOuterdrylandelder
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingOuterdrylandelder

- type: loadout
  id: N14ClothingOuterBandito
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterBandito

- type: loadout
  id: N14ClothingOuterforager
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterforager

- type: loadout
  id: N14ClothingOuterheadtaker
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterheadtaker

- type: loadout
  id: N14ClothingOuterhunter
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterhunter

- type: loadout
  id: N14ClothingOuterponcho
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterponcho

- type: loadout
  id: N14ClothingOutershaman
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOutershaman

- type: loadout
  id: N14ClothingOuterdrylandersimple
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingOuterdrylandersimple


- type: loadout
  id: N14ClothingDrylanderGoggles
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingDrylanderGoggles

- type: loadout
  id: N14ClothingHeadTakerwraps
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingHeadTakerwraps

- type: loadout
  id: N14ClothingTribalHeadWraps
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalHeadWraps

- type: loadout
  id: N14ClothingTribalHood
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalHood

- type: loadout
  id: N14ClothingTribalShamanHat
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalShamanHat

- type: loadout
  id: N14ClothingTribalShemagh
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalShemagh

- type: loadout
  id: N14ClothingTribalHunterHood
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalHunterHood

- type: loadout
  id: N14ClothingHeadHatEdlerSkullhelm
  category: Head
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingHeadHatEdlerSkullhelm

- type: loadout
  id: N14ClothingHeadHatEldersDamagedSkullHelm
  category: Head
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - TribalElder
  items:
    - N14ClothingHeadHatEldersDamagedSkullHelm

- type: loadout
  id: N14TribalHatchet
  category: Weapons
  cost: 3
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalHatchet

- type: loadout
  id: N14TribalMachete
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalMachete

- type: loadout
  id: N14TribalClub
  category: Weapons
  cost: 4
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMelee
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14TribalClub

- type: loadout
  id: N14ClothingTribalShamanHeadband
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterDepartmentRequirement
      departments:
        - Tribe
  items:
    - N14ClothingTribalShamanHeadband
