- type: loadout
  id: LoadoutNCRPinRecruit
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRCadet
  items:
    - ClothingNeckPinNCRRecruit

- type: loadout
  id: LoadoutNCRPinPrivate
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
  items:
    - ClothingNeckPinNCRPrivate

- type: loadout
  id: LoadoutNCRPinPrivate1st
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
    - !type:CharacterPlaytimeRequirement
      tracker: NCRSoldier
      min: 72000 # 20 hours veterancy unlock
  items:
    - ClothingNeckPinNCRPrivate1st

- type: loadout
  id: LoadoutNCRPinCorporal
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
    - !type:CharacterPlaytimeRequirement
      tracker: NCRSoldier
      min: 144000 # 40 hours veterancy unlock
  items:
    - ClothingNeckPinNCRCorporal

- type: loadout
  id: LoadoutNCRPinSpecialist
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
    - !type:CharacterPlaytimeRequirement
      tracker: NCRSoldier
      min: 216000 # 60 hours veterancy unlock
  items:
    - ClothingNeckPinNCRSpecialist

- type: loadout
  id: LoadoutNCRPinSergeant
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSGT
  items:
    - ClothingNeckPinNCRSergeant

- type: loadout
  id: LoadoutNCRPinSergeant1st
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSGT
    - !type:CharacterPlaytimeRequirement
      tracker: NCRNCO
      min: 72000 # 20 hours veterancy unlock
  items:
    - ClothingNeckPinNCRSergeant1st

- type: loadout
  id: LoadoutNCRPinMasterSergeant
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSGT
    - !type:CharacterPlaytimeRequirement
      tracker: NCRNCO
      min: 144000 # 40 hours veterancy unlock
  items:
    - ClothingNeckPinNCRMasterSergeant

- type: loadout
  id: LoadoutNCRPinSergeantMajor
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSGT
    - !type:CharacterPlaytimeRequirement
      tracker: NCRNCO
      min: 216000 # 60 hours veterancy unlock
  items:
    - ClothingNeckPinNCRSergeantMajor

- type: loadout
  id: LoadoutNCRPinSecondLieutenant
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRLT
  items:
    - ClothingNeckPinNCRSecondLieutenant

- type: loadout
  id: LoadoutNCRPinFirstlLieutenant
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRLT
    - !type:CharacterPlaytimeRequirement
      tracker: NCROfficer
      min: 72000 # 20 hours veterancy unlock
  items:
    - ClothingNeckPinNCRFirstlLieutenant

- type: loadout
  id: LoadoutNCRPinCaptain
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRLT
    - !type:CharacterPlaytimeRequirement
      tracker: NCROfficer
      min: 144000 # 40 hours veterancy unlock
  items:
    - ClothingNeckPinNCRCaptain

- type: loadout
  id: LoadoutNCRPinMajor
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRLT
    - !type:CharacterPlaytimeRequirement
      tracker: NCROfficer
      min: 216000 # 60 hours veterancy unlock
  items:
    - ClothingNeckPinNCRMajor

- type: loadout
  id: LoadoutNCRPinDoctor
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRMedic
  items:
    - ClothingNeckPinNCRDoctor

- type: loadout
  id: LoadoutNCRPinChiefPhysician
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRMedic
    - !type:CharacterPlaytimeRequirement
      tracker: NCRDoctor
      min: 72000 # 20 hours veterancy unlock
  items:
    - ClothingNeckPinNCRChiefPhysician

- type: loadout
  id: LoadoutNCRSnowHelmet
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetMetalSnow

- type: loadout
  id: LoadoutNCRWoodsHelmet
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetMetalWoods

- type: loadout
  id: LoadoutNCRDesertHelmet
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetMetalDesert

- type: loadout
  id: LoadoutNCRHoodedtHelmet
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetMetalHooded

- type: loadout
  id: LoadoutNCRHoodedtHelmetGreen
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetMetalHoodedGreen

- type: loadout
  id: LoadoutNCRBrodieHelmet
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRHelmetBrodie

- type: loadout
  id: LoadoutClothingEyesGlassesGoggles
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - N14ClothingEyesGlassesGoggles

- type: loadout
  id: LoadoutClothingHandsGlovesNCR
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - N14ClothingHandsGlovesNCR

- type: loadout
  id: LoadoutNCRMaskBalaclava
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRSGT
  items:
    - N14ClothingMaskBrownBalaclava

- type: loadout
  id: LoadoutClothingScoutCap
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
  items:
    - N14ClothingHeadHatNCRScoutCap
  
- type: loadout
  id: LoadoutClothingReconBeret
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutClothingMedicBeret
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - NCRMedic
  items:
    - N14ClothingHeadHatNCRBeretMedic

- type: loadout
  id: LoadoutClothingNcrDesertUniform
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutUniform
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - N14ClothingUniformNCRDesert

- type: loadout
  id: LoadoutClothingOuterNCRVestWoods
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRVestWoods

- type: loadout
  id: LoadoutClothingNcrSnowVest
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRVestSnow

- type: loadout
  id: LoadoutClothingNcrVestDesert
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRVestDesert

- type: loadout
  id: LoadoutClothingNcrPlateArmor
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRPlateWoods

- type: loadout
  id: LoadoutClothingNcrArmoredWinterCoat
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRArmoredWinterCoat

- type: loadout
  id: N14ClothingOuterNCRArmoredShortWinterCoat
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
  items:
    - N14ClothingOuterNCRArmoredWinterCoatShort

- type: loadout
  id: LoadoutClothingNcrAdvanceGasMask
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMask
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - ClothingMaskNcrAdvanceGasmask

- type: loadout
  id: LoadoutClothingNcrGasMask
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMask
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - ClothingMaskNcr

- type: loadout
  id: LoadoutClothingNcrBelt
  category: Items
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - ClothingBeltNCR

- type: loadout
  id: LoadoutClothingNcrPouches
  category: Items
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - ClothingBeltNCRPouches

- type: loadout
  id: LoadoutClothingNcrHarness
  category: Items
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - ClothingBeltNCRHarness

- type: loadout
  id: LoadoutClothingNcrLabcoat
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutOuter
    - !type:CharacterJobRequirement
      jobs:
        - NCRMedic
  items:
    - N14ClothingOuterCoatLab

- type: loadout
  id: LoadoutClothingNcrPlateMask
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutMask
    - !type:CharacterJobRequirement
      jobs:
        - NCRSoldier
        - NCRWS
        - NCREngineer
        - NCRCadet
        - NCRSGT
        - NCRMedic
        - NCRLT
  items:
    - N14ClothingMaskPlate