# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerVest
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerArmorB
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerArmorB

- type: loadout
  id: LoadoutNCRRangerDuster
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerDuster

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRmaskBroken
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerBroken

- type: loadout
  id: LoadoutNCRmaskCombat
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasCombat

# MARK: Ranger + Vet

- type: loadout
  id: LoadoutNCRhatB
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatBeret
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRuniformPants
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPants

- type: loadout
  id: LoadoutNCRuniformDesertPantsFull
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPantsFull

- type: loadout
  id: LoadoutNCRgloves
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHandsGlovesNCR

# misc
- type: loadout
  id: LoadoutNCRRangerMedkit
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MedkitCombatFilled

# MARK: Ranger Vet

- type: loadout
  id: LoadoutNCRuniformModif
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerModif

- type: loadout
  id: LoadoutNCRuniformBlue
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerBlue

- type: loadout
  id: LoadoutNCRuniformBlack
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranBlack

- type: loadout
  id: LoadoutNCRuniformRed
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranRed

- type: loadout
  id: LoadoutNCRuniformHelmetDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCRuniformMaskDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRuniformCombatDesert 
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerCombatDesert

- type: loadout
  id: LoadoutNCRRangerEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingOuterRangerEliteOld

- type: loadout
  id: LoadoutNCRRangerHelmetEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingHeadHatRangerHelmetEliteOld