- type: job
  id: Ranger
  setPreference: true
  name: job-name-ranger-ranking
  description: job-description-ranger-ranking
  playTimeTracker: Ranger
  startingGear: RangerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ranger-veteran
  canBeAntag: false
  access:
  - NCRCadet
  - NCRSoldier
  - NCRNCO
  - NCRRangerRanking

- type: startingGear
  id: RangerGear
  equipment:
    head: N14ClothingHeadHatRanger
    back: N14ClothingBackpackNCR
    jumpsuit: N14ClothingUniformRangerV2
    shoes: N14ClothingBootsLeather
    belt: ClothingBeltNCR
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterRangerArmor
    id: N14IDBadgeNCRDesertRanger
    ears: ClothingHeadsetSecurity #placeholder
  innerClothingSkirt: N14ClothingOfficerUniformNCR #placeholder

- type: playTimeTracker
  id: Ranger
