- type: job
  id: RangerVeteran
  setPreference: true
  name: job-name-ranger-veteran
  description: job-description-ranger-veteran
  playTimeTracker: RangerVeteran
  startingGear: RangerVeteranGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-ncr-captain
  canBeAntag: false
  accessGroups:
  - NCR

- type: startingGear
  id: RangerVeteranGear
  equipment:
    head: N14ClothingHeadHatRangerHelmetOld
    back: N14ClothingBackpackNCR
    jumpsuit: N14ClothingUniformRangerVeteran
    shoes: N14ClothingBootsCombat
    gloves: N14ClothingHandsGlovesCombat
    belt: ClothingBeltNCR
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterRangerCombat
    id: N14IDBadgeNCRDesertRangerElite
    ears: ClothingHeadsetSecurity #placeholder
  innerClothingSkirt: N14ClothingOfficerUniformNCR #placeholder

- type: playTimeTracker
  id: RangerVeteran
