- type: entity
  noSpawn: true
  parent: MobHuman
  id: N14MobHumanRanger
  name: Desert Ranger
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitary
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - SimpleNeutral

- type: entity
  noSpawn: true
  parent: MobHuman
  id: N14MobHumanRangerRecruit
  name: Desert Ranger Recruit
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerRecruitGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitary
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - SimpleNeutral

- type: entity
  noSpawn: true
  parent: MobHuman
  id: N14MobHumanRangerVeteran
  name: Desert Ranger Veteran
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerVeteranGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitaryLeader
      - NamesLastMilitary
    - type: NpcFactionMember
      factions:
      - SimpleNeutral

- type: entity
  noSpawn: true
  parent: MobHuman
  id: N14MobHumanRangerChief
  name: Desert Ranger Chief
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [RangerChiefGear]
    - type: RandomMetadata
      nameSegments:
      - NamesFirstMilitaryLeader
      - NamesLastMilitary
    - type: AutoImplant
      implants:
      - DeathAcidifierImplant
    - type: NpcFactionMember
      factions:
      - SimpleNeutral
