- type: job
  id: Ranger
  setPreference: false
  name: desert ranger
  description: job-description-ranger-ranking
  playTimeTracker: Ranger
  startingGear: RangerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ranger-veteran
  canBeAntag: false
  access:
  - NCRCadet
  - NCRSoldier
  - NCRNCO
  - NCRRanger

- type: startingGear
  id: RangerGear
  equipment:
    head: N14ClothingHeadHatRangerHelmetDesert
    back: N14ClothingBackpackMilitaryFilled
    jumpsuit: N14ClothingUniformRangerV2
    shoes: N14ClothingBootsLeather
    belt: ClothingBeltRevolverdesertfilled
    mask: ClothingMaskGasRangerDesert
    outerClothing: N14ClothingOuterRangerCombatDesert
    id: N14IDBadgeNCRDesertRanger
  innerClothingSkirt: N14ClothingOfficerUniformNCR #placeholder

- type: playTimeTracker
  id: Ranger
