- type: department
  id: BrotherhoodMidwest
  description: department-BrotherhoodMidwest-description
  color: "#3B72BF"
  roles:
  - BoSMidPaladinCommander
  - BoSMidSquire
  - BoSMidKnight
  - BoSMidPaladin
  - BoSMidScribe

- type: department
  id: BrotherhoodWashington
  description: department-BrotherhoodWashington-description
  color: "#a2000f"
  roles:
  - BoSWashingtonCommander
  - BoSWashingtonInitiate
  - BoSWashingtonKnight
  - BoSWashingtonPaladin
  - BoSWashingtonScribe

- type: department
  id: CaravanCompany
  description: department-CaravanCompany-description
  color: "#a1887f"
  roles:
  - CaravanLeader
  - CaravanTrader
  - CaravanGuard

- type: department
  id: NCR
  description: department-NCR-description
  color: "#fbc02d"
  roles:
  - NCRCadet
  - NCRSGT
  - NCRMedic
  - NCRLT
  - NCRSoldier
  - NCRWS
  - NCREngineer
  - NCRRanger
  - NCRRangerVeteran

#- type: department # Disabled until roles are implemented
#  id: Rangers
#  description: department-Ranger-description
#  color: "#3ab700"
#  roles:
#  - RangerRecruit
#  - Ranger
#  - RangerVeteran
#  - RangerChief

- type: department
  id: Tribe
  description: department-Tribe-description
  color: "#d69b3d"
  roles:
  - Tribal
  - TribalElder
  - TribalFarmer
  - TribalHealer

- type: department
  id: Vault
  description: department-Vault-description
  color: "#0d47a1"
  roles:
  - Overseer
  - VaultSecurity
  - VaultDoctor
  - VaultDweller
  - VaultEngineer

- type: department
  id: Wastelander
  description: department-Wastelander-description
  color: "#81c784"
  roles:
  - Survivor
  - Wastelander
  - WastelandChaplain
  - WastelandFarmer
  - WastelandMusician
  - WastelandScavenger

- type: department
  id: Townsfolk
  description: department-Townsfolk-description
  color: "#5c733a"
  roles:
  - Townsperson
  - TownDoctor
  - TownMechanic
  - TownShopkeeper
  - WastelandBartender # Moved from the Wastelander department, ID unchanged to avoid glitches for players who have it selected.
  - WastelandReporter # Moved from the Wastelander department, ID unchanged to avoid glitches for players who have it selected.
  - TownDeputy
  - TownSheriff
  - TownMayor

#- type: department #Disabled until roles are implemented.
#  id: Zetan
#  description: department-Zetan-description
#  color: "#7ec133"
#  roles:
#  - Zetan

#- type: department #Disabled until roles are implemented.
#  id: Followers
#  description: department-Followers-description
#  color: "#33a1c1"
#  roles:
#  - Followers
