# npcFactions determines which creatures are hostile to each other. Make use of this when making new creatures which are friendly to each other but not to others.
- type: npcFaction
  id: N14SimpleHostile
  hostile:
  - NanoTrasen
  - Syndicate
  - Passive
  - PetsNT
  - Zombie
  - Revolutionary
  - Wastelander
  - NCR
  - Raider
  - Brotherhood
  - Zetan
  - Followers

- type: npcFaction
  id: Wastelander
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Zombie
  - Revolutionary
  - Zetan
  - Raider

- type: npcFaction
  id: NCR
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Zombie
  - Revolutionary
  - Raider
  - Brotherhood
  - Zetan
  - Followers

- type: npcFaction
  id: Raider
  hostile:
  - NanoTrasen
  - Syndicate
  - Passive
  - PetsNT
  - Zombie
  - Revolutionary
  - Wastelander
  - NCR
  - Brotherhood
  - Zetan
  - Followers

- type: npcFaction
  id: Brotherhood
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Zombie
  - Revolutionary
  - Raider
  - NCR
  - Zetan
  - Followers

- type: npcFaction
  id: Zetan
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Zombie
  - Revolutionary
  - Raider
  - NCR
  - Wastelander
  - Townsperson
  - Followers

- type: npcFaction
  id: Followers
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Zombie
  - Revolutionary
  - Raider
  - NCR
  - Wastelander
  - Townsperson
  - Zetan
