# Nuclear 14 Role Trackers
# Jobs

- type: playTimeTracker
  id: BoSMidKnightCommander
  
- type: playTimeTracker
  id: BoSMidScribe
  
- type: playTimeTracker
  id: BoSWashingtonElder
  
- type: playTimeTracker
  id: BoSWashingtonKnight
  
- type: playTimeTracker
  id: BoSWashingtonPaladin
  
- type: playTimeTracker
  id: BoSWashingtonScribe
  
- type: playTimeTracker
  id: BoSWashingtonInitiate
  
- type: playTimeTracker
  id: CaravanLeader
  
- type: playTimeTracker
  id: CaravanTrader
  
- type: playTimeTracker
  id: NCRCadet
  
- type: playTimeTracker
  id: NCRNCO
  
- type: playTimeTracker
  id: NCROfficer
  
- type: playTimeTracker
  id: NCRSoldier
  
- type: playTimeTracker
  id: TribalHealer
  
- type: playTimeTracker
  id: Tribal
  
- type: playTimeTracker
  id: TribalElder
  
- type: playTimeTracker
  id: TribalFarmer
  
- type: playTimeTracker
  id: VaultSecurity
  
- type: playTimeTracker
  id: Overseer
  
- type: playTimeTracker
  id: VaultDoctor
  
- type: playTimeTracker
  id: VaultDweller
  
- type: playTimeTracker
  id: VaultEngineer
  
- type: playTimeTracker
  id: Wastelander
  
- type: playTimeTracker
  id: WastelandBartender
  
- type: playTimeTracker
  id: WastelandChaplain
  
- type: playTimeTracker
  id: Farmer
  
- type: playTimeTracker
  id: WastelandMusician
  
- type: playTimeTracker
  id: WastelandReporter
  
- type: playTimeTracker
  id: WastelandScavenger
  
- type: playTimeTracker
  id: Survivor