- type: job
  id: MountieSkirmisher
  setPreference: false
  overrideConsoleVisibility: false
  canBeAntag: false
  name: mountie skirmisher
  description: follow orders from your sergeant #need work
  playTimeTracker: MountieSkirmisher
  startingGear: MountieSkirmisherGear
  icon: "JobIconSecurityCadet"
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: MountieSkirmisherGear
  equipment:
    head: N14ClothingHeadHatHelmetRCMP
    back: N14ClothingBackpackMilitarySkirmisherFilled
    belt: N14TrenchClub
    jumpsuit: N14ClothingUniformJumpsuitRCMP
    shoes: N14ClothingBootsMountie
    gloves: N14ClothingHandsGlovesMountie
    mask: N14ClothingMaskSkirmisher
    outerClothing: N14ClothingOuterCombatArmorRCMP
    pocket1: N14WeaponRevolverWebley
    pocket2: N14CombatKnife
    suitstorage: N14WastelandPolearm
  innerClothingSkirt: N14ClothingUniformJumpsuitRCMP #placeholder
  satchel: N14ClothingBackpackMilitarySkirmisherFilled

- type: playTimeTracker
  id: MountieSkirmisher
