- type: job
  id: NCRQM
  setPreference: true
  name: NCR quartermaster
  description: Protect the armory and trade looted equipment with any wastelander.
  playTimeTracker: NCRQM
  startingGear: NCRQMGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCRCadet
  - NCRSoldier

- type: startingGear
  id: NCRQMGear
  equipment:
    head: N14ClothingHeadHatNCRBeretQM
    jumpsuit: N14ClothingUniformNCR
    shoes: N14ClothingBootsLeather
    id: N14IDNCRDogtag
  innerClothingSkirt: N14ClothingUniformNCR #placeholder

- type: playTimeTracker
  id: NCRQM
