- type: job
  id: NCRNCO
  setPreference: false # Delete line for RP
  name: job-name-ncr-nco
  description: job-description-ncr-nco
  playTimeTracker: NCRNCO
  startingGear: NCRNCOGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ncr
  canBeAntag: false
  access:
  - NCR3
  
- type: startingGear
  id: NCRNCOGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetal
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: N14ClothingShoesBootsJack
    eyes: ClothingEyesSunglasses
    outerClothing: N14ClothingOuterCombatArmor
    id: N14IDNCRDogtag
#    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRNCO