- type: entity
  parent: MobHuman
  id: N14MobHumanNCRCadet
  name: NCRCadet
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRCadetGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRDoctor
  name: NCRDoctor
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: NCRDoctorGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRMP
  name: NCRMP
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRMPGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRNCO
  name: NCRNCO
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRNCOGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCROfficer
  name: NCROfficer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCROfficerGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRQM
  name: NCRQM
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRQMGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRSoldier
  name: NCRSoldier
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRSoldierGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRRangerVeteran
  name: NCRRangerVeteran
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRRangerVeteranGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanNCRRanger
  name: NCRRanger
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [NCRRangerGear]
    - type: NpcFactionMember
      factions:
      - NanoTrasen

#TODO add pictures for the entitylist
