- type: job
  id: NCRCadet
  name: job-name-ncr-cadet
  playTimeTracker: NCRCadet
  startingGear: NCRCadetGear
  departments:
  - NCR
  icon: "SecurityCadet"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR1

- type: startingGear
  id: NCRCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
