- type: job
  id: NCRSoldier
  setPreference: false # Delete line for RP
  name: job-name-ncr-soldier
  description: job-description-ncr-soldier
  playTimeTracker: NCRSoldier
  startingGear: NCRSoldierGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR2

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetal
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: N14ClothingShoesBootsJack
    outerClothing: N14ClothingOuterLeatherArmor
    id: N14IDNCRDogtag
#    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRSoldier