- type: job
  id: NCRCadet
  setPreference: false # Delete line for RP
  name: job-name-ncr-cadet
  description: job-description-ncr-cadet
  playTimeTracker: NCRCadet
  startingGear: NCRCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR1

- type: startingGear
  id: NCRCadetGear
  equipment:
    head: N14ClothingHeadHatNCRSidecap
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: N14ClothingShoesBootsJack
    id: N14IDNCRDogtag
#    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltPoliceFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCRCadet