- type: job
  id: NCRSoldier
  name: job-name-ncr-soldier
  startingGear: NCRSoldierGear
  departments:
  - Security
  icon: "Warden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - Security

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
