- type: job
  id: NCRNCO
  name: job-name-ncr-nco
  startingGear: NCRNCOGear
  departments:
  - NCR
  icon: "SecurityOfficer"
  supervisors: job-supervisors-ncr
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: NCRNCOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetOld
    outerClothing: ClothingOuterVestKevlar
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
