- type: job
  id: NCROfficer
  setPreference: true
  name: job-name-ncr-officer
  description: job-description-ncr-officer
  playTimeTracker: NCROfficer
  weight: 10
  startingGear: NCROfficerGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR

- type: startingGear
  id: NCROfficerGear
  equipment:
    head: N14ClothingHeadHatNCRBeretOfficer
    jumpsuit: N14ClothingOfficerUniformNCR
    shoes: N14ClothingBootsLeather
    eyes: ClothingEyesGlassesSunglasses
    id: N14IDNCRDogtag
  innerClothingSkirt: N14ClothingOfficerUniformNCR #placeholder

- type: playTimeTracker
  id: NCROfficer
