- type: job
  id: NCRNCO
  name: job-name-ncr-nco
  playTimeTracker: NCRNCO
  startingGear: NCRNCOGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-ncr
  canBeAntag: false
  access:
  - NCR3
  
- type: startingGear
  id: NCRNCOGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetal
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesSunglasses
    outerClothing: N14ClothingOuterCombatArmor
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
