- type: job
  id: NCRSoldier
  name: job-name-ncr-soldier
  playTimeTracker: NCRSoldier
  startingGear: NCRSoldierGear
  icon: "Warden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR2

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetal
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterLeatherArmor
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
