- type: job
  id: NCRCadet
  setPreference: true
  name: job-name-ncr-cadet
  description: job-description-ncr-cadet
  playTimeTracker: NCRCadet
  startingGear: NCRCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCRCadet

- type: startingGear
  id: NCRCadetGear
  equipment:
    head: N14ClothingHeadHatNCRSidecap
    jumpsuit: N14ClothingUniformNCR
    shoes: N14ClothingBootsLeather
    id: N14IDNCRDogtag
    ears: ClothingHeadsetSecurity #placeholder
  innerClothingSkirt: N14ClothingUniformNCR #placeholder

- type: playTimeTracker
  id: NCRCadet
