- type: job
  id: NCROfficer
  setPreference: false # Delete line for RP
  name: job-name-ncr-officer
  description: job-description-ncr-officer
  playTimeTracker: NCROfficer
  weight: 10
  startingGear: NCROfficerGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR

- type: startingGear
  id: NCROfficerGear
  equipment:
    head: N14ClothingHeadHatNCRBeretOfficer
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: N14ClothingBackpackNCRFilled
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterCombatArmorMK2
    eyes: ClothingEyesSunglasses
    id: N14IDNCRDogtag
    ears: ClothingHeadsetAltSecurity #placeholder
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: N14ClothingBackpackSatchelNCRFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: NCROfficer