- type: loadout
  id: LoadoutNCRKitRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitRifleman

- type: loadout
  id: LoadoutNCRKitGunner
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitGunner

- type: loadout
  id: LoadoutNCRKitMarksman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMarksman

- type: loadout
  id: LoadoutNCRKitPointman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitPointman

- type: loadout
  id: LoadoutNCRKitMedic
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMedic

- type: loadout
  id: LoadoutNCRKitSpecialRifleman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialRifleman

- type: loadout
  id: LoadoutNCRKitSpecialAssault
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialAssault

- type: loadout
  id: LoadoutNCRKitSpecialGunner
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialGunner

- type: loadout
  id: LoadoutNCRKitSpecialPointman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialPointman

- type: loadout
  id: LoadoutRangerKitRifleman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerRecruit
        - Ranger
  items:
    - KitRiflemanRanger

- type: loadout
  id: LoadoutRangerKitMarksman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerRecruit
        - Ranger
  items:
    - KitMarksmanRanger

- type: loadout
  id: LoadoutRangerKitCQB
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerRecruit
        - Ranger
  items:
    - KitCQBRanger

- type: loadout
  id: LoadoutVeteranRangerKitRifleman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitRiflemanRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitHeavySniper
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitHeavySniperRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitTrailman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitTrailmanRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitAssault
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitAssaultRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitMarksman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitMarksmanRangerVeteran

- type: loadout
  id: LoadoutVeteranRangerKitCQB
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - RangerVeteran
  items:
    - KitCQBRangerVeteran
