- type: loadout
  id: LoadoutNCRKitRifleman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitRifleman
    
- type: loadout
  id: LoadoutNCRKitGunner
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitGunner
    
- type: loadout
  id: LoadoutNCRKitMarksman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMarksman
    
- type: loadout
  id: LoadoutNCRKitPointman
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitPointman
    
- type: loadout
  id: LoadoutNCRKitMedic
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRCadet
        - NCRSoldier
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitMedic
    
- type: loadout
  id: LoadoutNCRKitSpecialRifleman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialRifleman
    
- type: loadout
  id: LoadoutNCRKitSpecialAssault
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialAssault
    
- type: loadout
  id: LoadoutNCRKitSpecialGunner
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialGunner
    
- type: loadout
  id: LoadoutNCRKitSpecialPointman
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRNCO
        - NCROfficer
        - Survivor
  items:
    - KitSpecialPointman