# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerArmor
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerGun1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14Weapon50NcrRifle
    - MagazineBox50

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

# MARK: Ranger + Vet
- type: loadout
  id: LoadoutNCRRangerGun2
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponCarbine
    - LongMagazine5.56Rifle
    - LongMagazine5.56Rifle

- type: loadout
  id: LoadoutNCRRangerGun3
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponLeverRifle
    - MagazineBox308

- type: loadout
  id: LoadoutNCRRangerGun4
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponRiotShotgun
    - N14MagazineShotgun20
    - N14MagazineShotgun20

- type: loadout
  id: LoadoutNCRRangerGun5
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponLeverCarbine
    - MagazineBox44

- type: loadout
  id: LoadoutNCR5.56
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - LongMagazine5.56Rifle
    - LongMagazine5.56Rifle
    - MagazineBox5.56

- type: loadout
  id: LoadoutNCR50
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox50

- type: loadout
  id: LoadoutNCR308
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox308

- type: loadout
  id: LoadoutNCR20gauge
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MagazineShotgun20
    - N14MagazineShotgun20
    - MagazineBox20gauge

- type: loadout
  id: LoadoutNCR44
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox44
    - MagazineBox44

- type: loadout
  id: LoadoutNCRmaskBroken
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerBroken

- type: loadout
  id: LoadoutNCRmaskCombat
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - ClothingMaskGasCombat

- type: loadout
  id: LoadoutNCRhatB
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatGrey
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerGrey

- type: loadout
  id: LoadoutNCRhatGreyBanded
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerBanded

- type: loadout
  id: LoadoutNCRhatBeret
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRgloves
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHandsGlovesNCR

# MARK: Ranger Vet

- type: loadout
  id: LoadoutNCRVetGun1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponMarksman
    - Magazine7.62Rifle
    - Magazine7.62Rifle

- type: loadout
  id: LoadoutNCRVetGun2
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponAutoShotgun
    - N14MagazineShotgun12
    - N14MagazineShotgun12

- type: loadout
  id: LoadoutNCRVetGun3
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponAntiMateriel
    - MagazineBox50

- type: loadout
  id: LoadoutNCRVetGun4
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14WeaponBrushGun
    - MagazineBox45-70

- type: loadout
  id: LoadoutNCR762
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - Magazine7.62Rifle
    - Magazine7.62Rifle
    - MagazineBox7.62

- type: loadout
  id: LoadoutNCR12gauge
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MagazineShotgun12
    - N14MagazineShotgun12
    - N14MagazineBox12gauge

- type: loadout
  id: LoadoutNCR45-70
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - MagazineBox45-70

- type: loadout
  id: LoadoutNCRuniformModif
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerModif

- type: loadout
  id: LoadoutNCRuniformBlue
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerBlue

- type: loadout
  id: LoadoutNCRarmorFox
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerFox
    - N14ClothingHeadHatRangerHelmetFox

- type: loadout
  id: LoadoutNCRarmorBleached
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerCoat
    - N14ClothingHeadHatRangerHelmet
    - ClothingMaskGasRiot

- type: loadout
  id: LoadoutNCRarmorSand
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerCombatDesert
    - N14ClothingHeadHatRangerHelmetDesert
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRarmorPrice
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerPrice
    - N14ClothingHeadHatRangerHelmetPrice
    - ClothingMaskGasPrice
