- type: job
  id: WastelandBartender
  setPreference: false # Delete line for RP
  name: job-name-bartender
  playTimeTracker: WastelandBartender
  startingGear: WastelandBartenderGear
  icon: "Bartender"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelandBartenderGear
  equipment:
    head: ClothingHeadHatTophat
    jumpsuit: N14ClothingUniformJumpsuitBartenderAlt
    outerClothing: N14ClothingOuterLeatherArmor
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorBlack
  innerclothingskirt: N14ClothingUniformJumpsuitBartenderAlt #placeholder
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
