- type: job
  id: WastelandChaplain
  name: job-name-chaplain
  playTimeTracker: WastelandChaplain
  startingGear: WastelandChaplainGear
  icon: "Chaplain"
  supervisors: job-supervisors-wastelander
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: WastelandChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackChaplainFilled
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelChaplainFilled
  duffelbag: ClothingBackpackDuffelChaplainFilled
