- type: job
  id: WastelandMusician
  name: job-name-musician
  startingGear: MusicianGear
  departments:
  - Wastelanders
  icon: "Musician"
  supervisors: job-supervisors-hire
  access:
  - Maintenance
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: MusicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerPurple
    back: ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
    id: MusicianPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelMusicianFilled
  duffelbag: ClothingBackpackDuffelMusicianFilled
