- type: job
  id: WastelandReporter
  setPreference: false # Delete line for RP
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: WastelandReporter
  startingGear: WastelandReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelandReporterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitDetectiveAlt
    back: N14ClothingBackpackWastelanderFilled
#    shoes: ClothingShoesColorWhite
  innerclothingskirt: N14ClothingUniformJumpsuitDetectiveAlt
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled

- type: playTimeTracker
  id: WastelandReporter