- type: job
  id: WastelandReporter
  name: job-name-reporter
  playTimeTracker: WastelandReporter
  startingGear: WastelandReporterGear
  icon: "Reporter"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelandReporterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitDetectiveAlt
    back: N14ClothingBackpackWastelanderFilled
    shoes: ClothingShoesColorWhite
  innerclothingskirt: N14ClothingUniformJumpsuitDetectiveAlt
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
