- type: job
  id: Wastelander
  name: job-name-wastelander
  playTimeTracker: Wastelander
  startingGear: WastelanderGear
  departments:
  - Wastelanders
  icon: "Passenger"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
